const ideas = {

home:{
ru:[
"Устроить вечер настольных игр.",
"Приготовить вместе сложное блюдо, которое никогда не пробовали.",
"Построить крепость из подушек и одеял и смотреть там кино.",
"Устроить вечер дегустации сыров, вина или необычного чая.",
"Провести вечер без гаджетов при свечах.",
"Собрать вместе пазл на 1000 деталей.",
"Пройти тест на совместимость или 36 вопросов, чтобы влюбиться.",
"Написать письма в будущее друг другу и запечатать их на год.",
"Устроить домашний караоке-баттл.",
"Сделать вместе домашнюю пиццу с необычными начинками.",
"Устроить вечер спа дома: маски для лица, массаж и ванна.",
"Покрасить вместе футболки в стиле тай-дай.",
"Составить совместный плейлист нашей жизни.",
"Начать смотреть новый сериал с первой серии.",
"Устроить турнир в видеоигры.",
"Заказать еду, которую раньше боялись пробовать.",
"Устроить фотосессию в домашних образах.",
"Изучить основы массажа по видеоурокам.",
"Составить вместе карту желаний.",
"Устроить вечер чтения и читать друг другу вслух."
],

en:[
"Have a board game night together.",
"Cook a complicated dish together that you've never tried before.",
"Build a pillow and blanket fort and watch a movie inside.",
"Have a tasting night with cheese, wine, or unusual tea.",
"Spend an evening without gadgets, just candles and conversation.",
"Put together a 1000-piece puzzle together.",
"Take a compatibility test or the 36 questions to fall in love.",
"Write letters to your future selves and seal them for a year.",
"Have a home karaoke battle.",
"Make homemade pizza together with crazy toppings.",
"Have a home spa night with face masks, massage, and a bath.",
"DIY tie-dye some T-shirts together.",
"Create a shared playlist of your life together.",
"Start watching a new series from the first episode.",
"Have a video game tournament together.",
"Order food you've always been curious but afraid to try.",
"Do a fun photoshoot at home with different outfits.",
"Learn the basics of massage together from video tutorials.",
"Create a vision board together.",
"Have a reading night and read to each other out loud."
],

es:[
"Tener una noche de juegos de mesa juntos.",
"Cocinar juntos un plato complicado que nunca hayan probado.",
"Construir una fortaleza de almohadas y mantas y ver una película dentro.",
"Hacer una noche de degustación de quesos, vino o té especial.",
"Pasar una noche sin dispositivos, solo con velas.",
"Armar juntos un rompecabezas de 1000 piezas.",
"Hacer un test de compatibilidad o las 36 preguntas para enamorarse.",
"Escribir cartas para el futuro y guardarlas durante un año.",
"Hacer una batalla de karaoke en casa.",
"Preparar pizza casera juntos con ingredientes locos.",
"Tener una noche de spa en casa con mascarillas y masajes.",
"Teñir camisetas juntos estilo tie-dye.",
"Crear una playlist de nuestra vida juntos.",
"Empezar una nueva serie desde el primer episodio.",
"Hacer un torneo de videojuegos.",
"Pedir comida que siempre quisieron probar pero nunca se atrevieron.",
"Hacer una sesión de fotos divertida en casa.",
"Aprender juntos los fundamentos del masaje con videos.",
"Crear juntos un vision board o mapa de sueños.",
"Tener una noche de lectura y leerse en voz alta."
],

fr:[
"Organiser une soirée jeux de société.",
"Cuisiner ensemble un plat compliqué que vous n'avez jamais essayé.",
"Construire une cabane avec des coussins et des couvertures et regarder un film dedans.",
"Faire une soirée dégustation de fromages, de vin ou de thé spécial.",
"Passer une soirée sans gadgets, seulement à la lumière des bougies.",
"Assembler ensemble un puzzle de 1000 pièces.",
"Faire un test de compatibilité ou les 36 questions pour tomber amoureux.",
"Écrire des lettres pour le futur et les sceller pendant un an.",
"Faire une bataille de karaoké à la maison.",
"Préparer une pizza maison avec des garnitures originales.",
"Organiser une soirée spa à la maison avec masques et massage.",
"Teindre des T-shirts ensemble en style tie-dye.",
"Créer une playlist de notre vie ensemble.",
"Commencer une nouvelle série depuis le premier épisode.",
"Faire un tournoi de jeux vidéo.",
"Commander un plat que vous n'avez jamais osé essayer.",
"Faire une séance photo amusante à la maison.",
"Apprendre les bases du massage avec des vidéos.",
"Créer ensemble un vision board.",
"Organiser une soirée lecture et se lire à voix haute."
]
},

walk:{
ru:[
"Встретить рассвет на крыше или в парке.",
"Устроить пикник в живописном месте.",
"Покататься на велосипедах или самокатах.",
"Сходить на ночной сеанс в кино.",
"Посетить парк аттракционов и съесть сахарную вату.",
"Пойти в поход с палаткой на одну ночь.",
"Покататься на лодке или катамаране.",
"Сходить на блошиный рынок и купить друг другу небольшой сувенир.",
"Устроить день туриста в своем городе и сходить в музеи.",
"Покататься на коньках или роликах.",
"Покормить уток в парке или птиц в лесу.",
"Найти самый красивый вид на город.",
"Сходить в зоопарк или приют для животных и помочь им.",
"Поехать в соседний город на один день.",
"Устроить фотоохоту и сделать 10 тематических снимков города.",
"Сходить на фермерский рынок за продуктами.",
"Запустить небесный фонарик или воздушного змея.",
"Погулять под дождем с одним зонтом на двоих.",
"Найти секретный дворик в вашем городе.",
"Сходить на каток под открытым небом зимой.",
"Поиграть в снежки или слепить снеговика.",
"Собрать букет из полевых цветов.",
"Посмотреть на звезды за городом.",
"Пройтись по местам вашего первого свидания.",
"Сходить на ночную экскурсию."
],

en:[
"Watch the sunrise on a rooftop or in a park.",
"Have a picnic in a beautiful scenic spot.",
"Go for a ride on bicycles or scooters.",
"Go to a late-night movie screening.",
"Visit an amusement park and eat cotton candy.",
"Go camping for one night with a tent.",
"Ride a boat or paddle boat together.",
"Visit a flea market and buy each other a small souvenir.",
"Have a tourist day in your own city and visit museums.",
"Go ice skating or roller skating.",
"Feed ducks in the park or birds in the forest.",
"Find the most beautiful viewpoint in the city.",
"Visit a zoo or animal shelter and help the animals.",
"Take a one-day trip to a nearby city.",
"Do a photo hunt and take 10 themed photos around the city.",
"Visit a farmers market together.",
"Launch a sky lantern or fly a kite.",
"Walk in the rain sharing one umbrella.",
"Find a hidden courtyard in your city.",
"Go to an outdoor ice rink in winter.",
"Have a snowball fight or build a snowman.",
"Pick a bouquet of wildflowers.",
"Watch the stars outside the city.",
"Walk through the places of your first date.",
"Go on a night tour."
],

es:[
"Ver el amanecer en una azotea o en un parque.",
"Hacer un picnic en un lugar bonito.",
"Pasear en bicicletas o patinetes.",
"Ir a una sesión de cine nocturna.",
"Visitar un parque de atracciones y comer algodón de azúcar.",
"Ir de camping una noche con una tienda.",
"Pasear en barco o en pedaleta.",
"Ir a un mercadillo y comprarse un pequeño recuerdo.",
"Tener un día de turista en vuestra propia ciudad y visitar museos.",
"Ir a patinar sobre hielo o en patines.",
"Dar de comer a los patos en el parque o a los pájaros en el bosque.",
"Encontrar la vista más bonita de la ciudad.",
"Visitar un zoológico o un refugio de animales y ayudarles.",
"Hacer una excursión de un día a una ciudad cercana.",
"Hacer una búsqueda fotográfica y tomar 10 fotos temáticas de la ciudad.",
"Ir juntos a un mercado de agricultores.",
"Lanzar una linterna voladora o volar una cometa.",
"Pasear bajo la lluvia con un solo paraguas para los dos.",
"Encontrar un patio secreto en vuestra ciudad.",
"Ir a una pista de hielo al aire libre en invierno.",
"Jugar con bolas de nieve o hacer un muñeco de nieve.",
"Recoger un ramo de flores silvestres.",
"Mirar las estrellas fuera de la ciudad.",
"Pasear por los lugares de vuestra primera cita.",
"Hacer una excursión nocturna."
],

fr:[
"Regarder le lever du soleil sur un toit ou dans un parc.",
"Faire un pique-nique dans un endroit pittoresque.",
"Faire une balade à vélo ou en trottinette.",
"Aller à une séance de cinéma tard le soir.",
"Visiter un parc d'attractions et manger de la barbe à papa.",
"Partir camper une nuit avec une tente.",
"Faire un tour en bateau ou en pédalo.",
"Aller dans un marché aux puces et acheter un petit souvenir l'un pour l'autre.",
"Faire une journée touriste dans votre propre ville et visiter des musées.",
"Faire du patin à glace ou du roller.",
"Nourrir les canards dans le parc ou les oiseaux dans la forêt.",
"Trouver la plus belle vue sur la ville.",
"Visiter un zoo ou un refuge pour animaux et les aider.",
"Faire une excursion d'une journée dans une ville voisine.",
"Faire une chasse photo et prendre 10 photos thématiques de la ville.",
"Aller au marché fermier.",
"Lancer une lanterne volante ou faire voler un cerf-volant.",
"Se promener sous la pluie avec un seul parapluie pour deux.",
"Trouver une cour secrète dans votre ville.",
"Aller à une patinoire en plein air en hiver.",
"Faire une bataille de boules de neige ou un bonhomme de neige.",
"Ramasser un bouquet de fleurs sauvages.",
"Regarder les étoiles hors de la ville.",
"Marcher dans les lieux de votre premier rendez-vous.",
"Faire une visite guidée de nuit."
]
},

culture:{
ru:[
"Сходить на дегустацию вин.",
"Посетить джазовый концерт.",
"Сходить в галерею современного искусства.",
"Провести вечер в театре, надев лучшие наряды.",
"Попробовать себя в гончарном мастерстве.",
"Сходить на мастер-класс по рисованию в формате Art & Wine.",
"Сходить на стендап-шоу.",
"Посетить мастер-класс по парным танцам, например сальсе или танго.",
"Пойти в планетарий.",
"Устроить ужин в ресторане с кухней, которую никогда не пробовали.",
"Сходить на кулинарный мастер-класс.",
"Посетить квест-рум.",
"Пойти на спортивный матч, например футбол или хоккей.",
"Сходить в караоке-бар.",
"Посетить антикварный магазин.",
"Сходить в автокинотеатр.",
"Посетить ботанический сад.",
"Сходить поиграть в боулинг или бильярд.",
"Пойти на вечер поэзии.",
"Устроить Random Date и зайти в первое попавшееся кафе."
],

en:[
"Go to a wine tasting event.",
"Attend a jazz concert.",
"Visit a modern art gallery.",
"Spend an evening at the theater dressed in your best outfits.",
"Try pottery together.",
"Attend an Art & Wine painting class.",
"Go to a stand-up comedy show.",
"Take a couples dance class like salsa or tango.",
"Visit a planetarium.",
"Have dinner at a restaurant with a cuisine you've never tried before.",
"Take a cooking class together.",
"Visit an escape room.",
"Go to a sports game like football or hockey.",
"Go to a karaoke bar.",
"Visit an antique shop.",
"Go to a drive-in movie theater.",
"Visit a botanical garden.",
"Go bowling or play billiards.",
"Attend a poetry night.",
"Have a random date and walk into the first café you see."
],

es:[
"Ir a una degustación de vinos.",
"Asistir a un concierto de jazz.",
"Visitar una galería de arte moderno.",
"Pasar una noche en el teatro con sus mejores outfits.",
"Probar la cerámica o alfarería juntos.",
"Ir a una clase de pintura estilo Art & Wine.",
"Ir a un espectáculo de stand-up.",
"Tomar una clase de baile en pareja como salsa o tango.",
"Ir a un planetario.",
"Cenar en un restaurante con una cocina que nunca hayan probado.",
"Tomar una clase de cocina juntos.",
"Visitar una sala de escape.",
"Ir a un partido deportivo como fútbol o hockey.",
"Ir a un bar de karaoke.",
"Visitar una tienda de antigüedades.",
"Ir a un autocine.",
"Visitar un jardín botánico.",
"Ir a jugar bolos o billar.",
"Asistir a una noche de poesía.",
"Tener una cita aleatoria y entrar en el primer café que encuentren."
],

fr:[
"Aller à une dégustation de vins.",
"Assister à un concert de jazz.",
"Visiter une galerie d'art contemporain.",
"Passer une soirée au théâtre en portant vos plus belles tenues.",
"Essayer la poterie ensemble.",
"Participer à un atelier de peinture Art & Wine.",
"Aller à un spectacle de stand-up.",
"Prendre un cours de danse en couple comme la salsa ou le tango.",
"Aller au planétarium.",
"Dîner dans un restaurant avec une cuisine que vous n'avez jamais essayée.",
"Participer à un cours de cuisine ensemble.",
"Visiter une escape room.",
"Aller voir un match sportif comme le football ou le hockey.",
"Aller dans un bar karaoké.",
"Visiter une boutique d'antiquités.",
"Aller dans un cinéma drive-in.",
"Visiter un jardin botanique.",
"Aller jouer au bowling ou au billard.",
"Assister à une soirée poésie.",
"Faire une Random Date et entrer dans le premier café trouvé."
]
},

extreme:{
ru:[
"Прыгнуть с тарзанки или с парашютом.",
"Пойти на картинг.",
"Посетить аквапарк.",
"Попробовать полет в аэротрубе.",
"Пострелять в тире или сходить в лазертаг.",
"Сходить на скалодром.",
"Покататься на лошадях.",
"Попробовать сап-бординг.",
"Посетить комнату ярости, где можно бить посуду.",
"Пойти на ночной квест с актерами в стиле хоррор.",
"Устроить тест-драйв автомобиля мечты.",
"Полетать на воздушном шаре.",
"Сходить на урок дайвинга в бассейне.",
"Попробовать встать на сноуборд или лыжи.",
"Покататься на квадроциклах."
],

en:[
"Go bungee jumping or skydiving.",
"Go kart racing.",
"Visit a water park.",
"Try indoor skydiving in a wind tunnel.",
"Go to a shooting range or play laser tag.",
"Visit a climbing gym.",
"Go horseback riding.",
"Try stand-up paddleboarding.",
"Visit a rage room where you can smash things.",
"Go to a nighttime horror quest with actors.",
"Test-drive your dream car.",
"Take a hot air balloon ride.",
"Try a diving lesson in a swimming pool.",
"Try snowboarding or skiing.",
"Ride quad bikes or ATVs."
],

es:[
"Hacer bungee jumping o saltar en paracaídas.",
"Ir a correr en karts.",
"Visitar un parque acuático.",
"Probar un vuelo en túnel de viento.",
"Ir a un campo de tiro o jugar laser tag.",
"Ir a un rocódromo.",
"Montar a caballo.",
"Probar paddle surf.",
"Visitar una sala de destrucción donde se pueden romper cosas.",
"Ir a un juego de terror nocturno con actores.",
"Probar el coche de tus sueños en un test drive.",
"Volar en globo aerostático.",
"Tomar una clase de buceo en una piscina.",
"Probar snowboard o esquí.",
"Pasear en quads o vehículos ATV."
],

fr:[
"Faire du saut à l'élastique ou du parachutisme.",
"Faire du karting.",
"Visiter un parc aquatique.",
"Essayer un vol en soufflerie.",
"Aller dans un stand de tir ou jouer au laser game.",
"Aller dans une salle d'escalade.",
"Faire de l'équitation.",
"Essayer le stand-up paddle.",
"Visiter une rage room où l'on peut casser des objets.",
"Participer à un jeu d'horreur nocturne avec des acteurs.",
"Faire un essai de la voiture de vos rêves.",
"Faire un vol en montgolfière.",
"Prendre un cours de plongée dans une piscine.",
"Essayer le snowboard ou le ski.",
"Faire une balade en quad."
]
},

romantic:{
ru:[
"Устроить свидание вслепую, где один выбирает место, а другой не знает куда едет.",
"Забронировать отель в своем же городе на одну ночь.",
"Купить билеты в кино на места для поцелуев.",
"Сделать совместную татуировку или временную.",
"Устроить фотосессию Love Story.",
"Обменяться книгами, которые изменили вашу жизнь.",
"Сделать друг другу чековую книжку желаний.",
"Приготовить ужин из пяти блюд вместе.",
"Сходить на парную йогу.",
"Устроить пикник на балконе.",
"Посадить вместе дерево или комнатный цветок.",
"Устроить вечер воспоминаний и смотреть старые фото и видео.",
"Сделать капсулу времени и спрятать её.",
"Сходить на дегустацию парфюмерии и выбрать ароматы друг для друга.",
"Устроить свидание в стиле 20-х годов или другой эпохи.",
"Сделать слепок своих рук из гипса.",
"Подарить друг другу подарки, сделанные своими руками.",
"Провести целый день, говоря друг другу только «да».",
"Уехать на выходные в незнакомый город без плана.",
"Придумать свой личный праздник и отмечать его каждый год."
],

en:[
"Have a blind date where one person chooses the place and the other doesn't know where they're going.",
"Book a hotel in your own city for one night.",
"Buy cinema tickets for the back row or 'kiss seats'.",
"Get matching tattoos or temporary ones together.",
"Do a Love Story photoshoot together.",
"Exchange books that changed your life.",
"Make each other a coupon book of wishes.",
"Cook a five-course dinner together.",
"Try couples yoga.",
"Have a picnic on your balcony.",
"Plant a tree or a houseplant together.",
"Have a nostalgia evening looking through old photos and videos.",
"Create a time capsule and hide it.",
"Go to a perfume tasting and choose fragrances for each other.",
"Have a themed date in the style of the 1920s or another era.",
"Make a plaster cast of your hands together.",
"Give each other handmade gifts.",
"Spend a whole day saying only 'yes' to each other.",
"Travel to an unfamiliar city for the weekend without a plan.",
"Create your own personal holiday and celebrate it every year."
],

es:[
"Tener una cita a ciegas donde uno elige el lugar y el otro no sabe a dónde van.",
"Reservar un hotel en vuestra propia ciudad por una noche.",
"Comprar entradas de cine en los asientos del fondo para parejas.",
"Hacerse un tatuaje juntos o uno temporal.",
"Hacer una sesión de fotos estilo Love Story.",
"Intercambiar libros que cambiaron vuestra vida.",
"Hacer un cuaderno de cupones de deseos para el otro.",
"Cocinar juntos una cena de cinco platos.",
"Probar yoga en pareja.",
"Hacer un picnic en el balcón.",
"Plantar juntos un árbol o una planta.",
"Tener una noche de recuerdos viendo fotos y videos antiguos.",
"Crear una cápsula del tiempo y esconderla.",
"Ir a una degustación de perfumes y elegir fragancias el uno para el otro.",
"Tener una cita temática estilo años 20 u otra época.",
"Hacer un molde de vuestras manos con yeso.",
"Regalarse regalos hechos a mano.",
"Pasar un día entero diciéndose solo 'sí'.",
"Ir a una ciudad desconocida el fin de semana sin plan.",
"Inventar vuestro propio día especial y celebrarlo cada año."
],

fr:[
"Faire un rendez-vous à l'aveugle où l'un choisit l'endroit et l'autre ne sait pas où il va.",
"Réserver un hôtel dans votre propre ville pour une nuit.",
"Acheter des billets de cinéma pour les places du fond pour s'embrasser.",
"Faire un tatouage ensemble ou un tatouage temporaire.",
"Faire une séance photo Love Story.",
"Échanger des livres qui ont changé votre vie.",
"Créer un carnet de coupons de souhaits pour l'autre.",
"Cuisiner ensemble un dîner de cinq plats.",
"Essayer le yoga en couple.",
"Faire un pique-nique sur le balcon.",
"Planter ensemble un arbre ou une plante.",
"Passer une soirée souvenirs en regardant de vieilles photos et vidéos.",
"Créer une capsule temporelle et la cacher.",
"Aller à une dégustation de parfums et choisir des fragrances l'un pour l'autre.",
"Faire un rendez-vous dans le style des années 20 ou d'une autre époque.",
"Faire un moulage de vos mains en plâtre.",
"Offrir des cadeaux faits à la main l'un à l'autre.",
"Passer une journée entière à se dire seulement 'oui'.",
"Partir un week-end dans une ville inconnue sans plan.",
"Inventer votre propre fête et la célébrer chaque année."
]
}

}
