const likelyCards = {

ru:[
"Кто скорее всего напишет бывшему в три часа ночи «просто проверить, как ты»?",
"Кто скорее всего поставит лайк всем сторис crush за один вечер?",
"Кто скорее всего притворится пьяным, чтобы поцеловать кого-то?",
"Кто скорее всего забудет имя человека после первого поцелуя?",
"Кто скорее всего отправит мем вместо нормального ответа на флирт?",
"Кто скорее всего пойдёт на свидание только ради бесплатной еды?",
"Кто скорее всего напишет «ты сегодня огонь 🔥» в 2:47 ночи?",
"Кто скорее всего сделает скриншот переписки и покажет всей компании?",
"Кто скорее всего будет смотреть сторис crush первым делом утром?",
"Кто скорее всего лайкнет старый пост, чтобы напомнить о себе?",
"Кто скорее всего притворится, что ему холодно, чтобы его обняли?",
"Кто скорее всего отправит слишком много сердечек за один вечер?",
"Кто скорее всего случайно коснётся ноги под столом и сделает вид, что ничего не было?",
"Кто скорее всего напишет «я скучаю» после одного свидания?",
"Кто скорее всего поставит статус «всё сложно», намекая на кого-то?",
"Кто скорее всего будет улыбаться телефону от одного сообщения?",
"Кто скорее всего притворится, что нравится та же музыка, что и crush?",
"Кто скорее всего отправит «пришли фотку» без видимой причины?",
"Кто скорее всего краснеет от одного долгого взгляда в глаза?",
"Кто скорее всего напишет «спокойной ночи ❤️» человеку, с которым почти не общается?",
"Кто скорее всего поцелует кого-то в лифте, когда могли зайти в любой момент?",
"Кто скорее всего скажет «ты мне снился или снилась» после одного свидания?",
"Кто скорее всего отправит голосовое с дурацким голосом, чтобы рассмешить crush?",
"Кто скорее всего поставит реакцию 🔥 на сторис с декольте или прессом?",
"Кто скорее всего будет флиртовать с баристой или официантом ради бонусов?",
"Кто скорее всего напишет «приходи, я один дома» после часа ночи?",
"Кто скорее всего отправит фото «случайно» с голым торсом или в белье?",
"Кто скорее всего краснеет от комплимента про задницу или грудь?",
"Кто скорее всего поцелует кого-то в туалете бара или клуба?",
"Кто скорее всего напишет «хочу тебя увидеть» в четыре утра?",
"Кто скорее всего притворится, что уронил телефон, чтобы наклониться ближе?",
"Кто скорее всего будет фантазировать о поцелуе с кем-то из компании прямо сейчас?",
"Кто скорее всего отправит голосовое со стонами «в шутку»?",
"Кто скорее всего скажет «ты выглядишь так, будто только что трахался или трахалась»?",
"Кто скорее всего поставит на аватарку фото, где видно больше, чем обычно?",
"Кто скорее всего напишет «я уже мокрый или мокрая» в групповой чат по пьяни?",
"Кто скорее всего будет смотреть на чьи-то губы и думать «хочу их на себе»?",
"Кто скорее всего поцелует кого-то на балконе, пока все внутри?",
"Кто скорее всего отправит «думаю о тебе и трогаю себя» не тому человеку?",
"Кто скорее всего краснеет от шутки «а ты громко стонешь»?",
"Кто скорее всего напишет «приходи в одном белье» в личку?",
"Кто скорее всего будет фантазировать о сексе в машине с кем-то из компании?",
"Кто скорее всего скажет «я бы тебя трахнул или трахнула» в шутку в компании?",
"Кто скорее всего отправит фото попки или члена «на спор»?",
"Кто скорее всего краснеет от случайного касания в интимной зоне?",
"Кто скорее всего поставит сторис в нижнем белье с подписью «ночь»?",
"Кто скорее всего напишет «хочу услышать, как ты стонешь моё имя»?",
"Кто скорее всего поцелует кого-то в чужом подъезде?",
"Кто скорее всего отправит «кончил или кончила, думая о тебе» бывшему?",
"Кто скорее всего будет фантазировать о том, чтобы остаться наедине после тусы?",
 "Кто скорее всего скажет «ты самый или самая горячий или горячая» в чат?",
"Кто скорее всего отправит стикер с поцелуем вместо нормального текста?",
"Кто скорее всего краснеет просто потому что кто-то сказал «ты опасно выглядишь»?",
"Кто скорее всего напишет «давай повторим ту ночь» через год?",
"Кто скорее всего будет флиртовать в комментариях под постом crush?",
"Кто скорее всего притворится, что ему нравится грубый секс, чтобы не обидеть?",
"Кто скорее всего отправит «хочу тебя так сильно, что уже…»?",
"Кто скорее всего посмотрит порно и подумает «а с кем-то здесь это было бы круто»?",
"Кто скорее всего напишет «ты бы мне подошёл или подошла для одной ночи»?",
"Кто скорее всего краснеет от фразы «я бы тебя отлизал или отлизала прямо сейчас»?",
"Кто скорее всего отправит голосовое с оргазмом вместо спокойного сообщения?",
"Кто скорее всего будет фантазировать о тройничке с двумя из компании?",
"Кто скорее всего скажет «ты выглядишь как после хорошего траха»?",
"Кто скорее всего напишет «хочу почувствовать тебя внутри»?",
"Кто скорее всего отправит фото после душа с подписью «только что»?",
"Кто скорее всего краснеет от комплимента «у тебя крутая задница»?",
"Кто скорее всего поцелует кого-то в машине на светофоре?",
"Кто скорее всего поставит реакцию 😈 на откровенную сторис?",
"Кто скорее всего напишет «приходи, я жду тебя голым или голой»?",
"Кто скорее всего будет смотреть на чьи-то руки и думать «хочу, чтобы они были на мне»?",
"Кто скорее всего отправит «я уже трогаю себя, думая о тебе»?",
"Кто скорее всего фантазирует о сексе на кухне этой квартиры?",
"Кто скорее всего скажет «я бы тебя взял или взяла жёстко» в шутку?",
"Кто скорее всего краснеет от шутки про размер или глубину?",
"Кто скорее всего напишет «давай без презерватива, я доверяю»?",
"Кто скорее всего отправит видео, где видно, как трогает себя?",
"Кто скорее всего будет фантазировать о 69 с кем-то из здесь?",
"Кто скорее всего скажет «ты выглядишь как шлюшка сегодня»?",
"Кто скорее всего напишет «хочу, чтобы ты кончил или кончила на меня»?",
"Кто скорее всего поцелует кого-то в гардеробе на вечеринке?",
"Кто скорее всего отправит «хочу, чтобы ты меня взял или взяла сзади»?",
"Кто скорее всего краснеет от мысли, что все знают его или её фантазии?",
"Кто скорее всего напишет «ты сводишь меня с ума в постели»?",
"Кто скорее всего будет фантазировать о сексе в лифте с кем-то здесь?",
"Кто скорее всего отправит «я кончаю от одной мысли о тебе»?",
"Кто скорее всего скажет «давай займёмся этим без слов»?",
"Кто скорее всего краснеет от фразы «ты выглядишь так, будто хочешь секса»?",
"Кто скорее всего напишет «хочу попробовать с тобой всё»?",
"Кто скорее всего отправит фото сосков или члена со словами «оцени»?",
"Кто скорее всего будет фантазировать о БДСМ с кем-то из компании?",
"Кто скорее всего скажет «я бы тебя отымел или отымела до утра»?",
"Кто скорее всего краснеет от лёгкого укуса за шею в шутку?",
"Кто скорее всего напишет «хочу почувствовать твой язык»?",
"Кто скорее всего отправит «пришли сиськи или член» в групповой чат?",
"Кто скорее всего будет фантазировать о сексе в душе после вечеринки?",
"Кто скорее всего скажет «ты бы мне подошёл для грязных фантазий»?",
"Кто скорее всего краснеет от «я бы тебя трахнул или трахнула прямо здесь»?",
"Кто скорее всего напишет «давай повторим, но уже без одежды»?",
"Кто скорее всего отправит «хочу тебя так, что уже не могу»?",
"Кто скорее всего станет легендой вечера после этой игры и выпьет больше всех?" 
],

en:[
"Who is most likely to text their ex at 3 AM just to check how they are?",
"Who is most likely to like every story their crush posts in one evening?",
"Who is most likely to pretend to be drunk just to kiss someone?",
"Who is most likely to forget someone's name after the first kiss?",
"Who is most likely to send a meme instead of a real reply to flirting?",
"Who is most likely to go on a date just for free food?",
"Who is most likely to text 'you look hot tonight 🔥' at 2:47 AM?",
"Who is most likely to screenshot a chat and show it to everyone?",
"Who is most likely to check their crush's stories first thing in the morning?",
"Who is most likely to like an old post just to remind someone they exist?",
"Who is most likely to pretend they're cold just to get a hug?",
"Who is most likely to send way too many hearts in one night?",
"Who is most likely to touch someone's leg under the table and pretend nothing happened?",
"Who is most likely to text 'I miss you' after one date?",
"Who is most likely to set their status to 'it's complicated' hinting at someone?",
"Who is most likely to smile at their phone because of one message?",
"Who is most likely to pretend they like the same music as their crush?",
"Who is most likely to text 'send me a photo' for no reason?",
"Who is most likely to blush after long eye contact?",
"Who is most likely to text 'good night ❤️' to someone they barely talk to?",
"Who is most likely to kiss someone in an elevator where anyone could walk in?",
"Who is most likely to say 'I dreamed about you' after one date?",
"Who is most likely to send a silly voice message to make their crush laugh?",
"Who is most likely to react 🔥 to a revealing story?",
"Who is most likely to flirt with a barista or waiter for perks?",
"Who is most likely to text 'come over, I'm home alone' after midnight?",
"Who is most likely to send a 'casual' shirtless or underwear photo?",
"Who is most likely to blush at a compliment about their butt or chest?",
"Who is most likely to kiss someone in a bar or club bathroom?",
"Who is most likely to text 'I want to see you' at 4 AM?",
"Who is most likely to pretend they dropped their phone just to lean closer?",
"Who is most likely to fantasize about kissing someone in the group right now?",
"Who is most likely to send a moaning voice message as a joke?",
"Who is most likely to say 'you look like you just had sex'?",
"Who is most likely to set a profile photo that's more revealing than usual?",
"Who is most likely to text 'I'm already wet or hard' in a group chat while drunk?",
"Who is most likely to look at someone's lips and think 'I want them on me'?",
"Who is most likely to kiss someone on the balcony while everyone else is inside?",
"Who is most likely to accidentally send 'thinking about you while touching myself' to the wrong person?",
"Who is most likely to blush at the joke 'do you moan loudly?'",
"Who is most likely to text 'come over wearing only underwear'?",
"Who is most likely to fantasize about sex in a car with someone here?",
"Who is most likely to jokingly say 'I'd totally sleep with you' in the group?",
"Who is most likely to send a butt or dick photo as a dare?",
"Who is most likely to blush from an accidental intimate touch?",
"Who is most likely to post a story in underwear captioned 'night'?",
"Who is most likely to text 'I want to hear you moan my name'?",
"Who is most likely to kiss someone in a random building entrance?",
"Who is most likely to text an ex 'I finished thinking about you'?",
"Who is most likely to fantasize about staying alone together after the party?",
 "Who is most likely to say 'you're the hottest one here' in the chat?",
"Who is most likely to send a kiss sticker instead of a real message?",
"Who is most likely to blush just because someone said 'you look dangerously hot'?",
"Who is most likely to text 'let's repeat that night' a year later?",
"Who is most likely to flirt in the comments under their crush's post?",
"Who is most likely to pretend they enjoy rough sex just to avoid hurting someone's feelings?",
"Who is most likely to text 'I want you so badly that already…'?",
"Who is most likely to watch porn and think 'doing that with someone here would be hot'?",
"Who is most likely to say 'you'd be perfect for a one-night thing'?",
"Who is most likely to blush at 'I'd go down on you right now'?",
"Who is most likely to send a voice message with fake orgasm sounds instead of a normal message?",
"Who is most likely to fantasize about a threesome with two people from the group?",
"Who is most likely to say 'you look like you just had amazing sex'?",
"Who is most likely to text 'I want to feel you inside me'?",
"Who is most likely to send a post-shower photo with the caption 'just now'?",
"Who is most likely to blush at 'you have an amazing ass'?",
"Who is most likely to kiss someone in a car at a red light?",
"Who is most likely to react 😈 to a revealing story?",
"Who is most likely to text 'come over, I'm waiting for you naked'?",
"Who is most likely to look at someone's hands and think 'I want them on me'?",
"Who is most likely to send 'I'm touching myself thinking about you'?",
"Who is most likely to fantasize about sex in this apartment's kitchen?",
"Who is most likely to jokingly say 'I'd take you hard'?",
"Who is most likely to blush at jokes about size or depth?",
"Who is most likely to text 'let's do it without protection, I trust you'?",
"Who is most likely to send a video of themselves touching themselves?",
"Who is most likely to fantasize about 69 with someone here?",
"Who is most likely to say 'you look like a total tease tonight'?",
"Who is most likely to text 'I want you to finish on me'?",
"Who is most likely to kiss someone in the coat room at a party?",
"Who is most likely to text 'I want you to take me from behind'?",
"Who is most likely to blush thinking everyone knows their fantasies?",
"Who is most likely to text 'you drive me crazy in bed'?",
"Who is most likely to fantasize about sex in an elevator with someone here?",
"Who is most likely to text 'I finish just thinking about you'?",
"Who is most likely to say 'let's do it without saying a word'?",
"Who is most likely to blush at 'you look like you want sex right now'?",
"Who is most likely to text 'I want to try everything with you'?",
"Who is most likely to send a nipple or dick photo saying 'rate it'?",
"Who is most likely to fantasize about BDSM with someone in the group?",
"Who is most likely to say 'I'd keep you busy all night'?",
"Who is most likely to blush from a playful neck bite?",
"Who is most likely to text 'I want to feel your tongue'?",
"Who is most likely to send 'send boobs or dick' in the group chat?",
"Who is most likely to fantasize about shower sex after the party?",
"Who is most likely to say 'you'd be perfect for my dirty fantasies'?",
"Who is most likely to blush at 'I'd have sex with you right here'?",
"Who is most likely to text 'let's do it again, but this time without clothes'?",
"Who is most likely to send 'I want you so badly I can't handle it'?",
"Who is most likely to become the legend of the night after this game and drink the most?" 
],

es:[
"¿Quién es más probable que escriba a su ex a las 3 de la mañana solo para preguntar cómo está?",
"¿Quién es más probable que dé like a todas las historias de su crush en una noche?",
"¿Quién es más probable que finja estar borracho para besar a alguien?",
"¿Quién es más probable que olvide el nombre de alguien después del primer beso?",
"¿Quién es más probable que envíe un meme en lugar de responder al coqueteo?",
"¿Quién es más probable que vaya a una cita solo por la comida gratis?",
"¿Quién es más probable que escriba 'te ves increíble 🔥' a las 2:47 de la mañana?",
"¿Quién es más probable que haga una captura de pantalla del chat y la enseñe a todos?",
"¿Quién es más probable que vea las historias de su crush al despertar?",
"¿Quién es más probable que dé like a una publicación antigua para llamar la atención?",
"¿Quién es más probable que finja tener frío para recibir un abrazo?",
"¿Quién es más probable que envíe demasiados corazones en una sola noche?",
"¿Quién es más probable que toque una pierna bajo la mesa y actúe como si nada?",
"¿Quién es más probable que escriba 'te extraño' después de una cita?",
"¿Quién es más probable que ponga el estado 'es complicado' insinuando algo?",
"¿Quién es más probable que sonría al teléfono por un solo mensaje?",
"¿Quién es más probable que finja que le gusta la misma música que su crush?",
"¿Quién es más probable que escriba 'envía una foto' sin razón?",
"¿Quién es más probable que se sonroje después de una mirada larga?",
"¿Quién es más probable que escriba 'buenas noches ❤️' a alguien con quien casi no habla?",
"¿Quién es más probable que bese a alguien en un ascensor?",
"¿Quién es más probable que diga 'soñé contigo' después de una cita?",
"¿Quién es más probable que envíe un audio gracioso para hacer reír a su crush?",
"¿Quién es más probable que reaccione 🔥 a una historia provocativa?",
"¿Quién es más probable que coquetee con un barista o camarero por beneficios?",
"¿Quién es más probable que escriba 'ven, estoy solo o sola en casa' después de medianoche?",
"¿Quién es más probable que envíe una foto en ropa interior como si fuera casual?",
"¿Quién es más probable que se sonroje por un cumplido sobre su trasero o pecho?",
"¿Quién es más probable que bese a alguien en el baño de un bar o club?",
"¿Quién es más probable que escriba 'quiero verte' a las 4 de la mañana?",
"¿Quién es más probable que finja que se le cayó el teléfono para acercarse?",
"¿Quién es más probable que fantasee con besar a alguien del grupo ahora mismo?",
"¿Quién es más probable que envíe un audio con gemidos como broma?",
"¿Quién es más probable que diga 'pareces como si acabaras de tener sexo'?",
"¿Quién es más probable que ponga una foto de perfil más provocativa de lo normal?",
"¿Quién es más probable que escriba algo provocativo en un chat grupal estando borracho?",
"¿Quién es más probable que mire los labios de alguien y piense 'los quiero sobre mí'?",
"¿Quién es más probable que bese a alguien en un balcón mientras los demás están dentro?",
"¿Quién es más probable que envíe un mensaje íntimo a la persona equivocada?",
"¿Quién es más probable que se sonroje con la broma '¿gimes fuerte?'",
"¿Quién es más probable que escriba 'ven usando solo ropa interior'?",
"¿Quién es más probable que fantasee con sexo en un coche con alguien del grupo?",
"¿Quién es más probable que diga en broma 'tendría sexo contigo'?",
"¿Quién es más probable que envíe una foto íntima por un reto?",
"¿Quién es más probable que se sonroje por un toque íntimo accidental?",
"¿Quién es más probable que publique una historia en ropa interior con la palabra 'noche'?",
"¿Quién es más probable que escriba 'quiero oírte gemir mi nombre'?",
"¿Quién es más probable que bese a alguien en la entrada de un edificio?",
"¿Quién es más probable que escriba a su ex 'terminé pensando en ti'?",
"¿Quién es más probable que fantasee con quedarse a solas después de la fiesta?",
 "¿Quién es más probable que diga 'eres el o la más sexy aquí' en el chat?",
"¿Quién es más probable que envíe un sticker de beso en lugar de texto?",
"¿Quién es más probable que se sonroje porque alguien dijo 'te ves peligrosamente sexy'?",
"¿Quién es más probable que escriba 'repitamos aquella noche' un año después?",
"¿Quién es más probable que coquetee en los comentarios de la publicación de su crush?",
"¿Quién es más probable que finja que le gusta el sexo rudo para no ofender?",
"¿Quién es más probable que envíe 'te deseo tanto que ya…'?",
"¿Quién es más probable que vea porno y piense 'hacer eso con alguien aquí sería increíble'?",
"¿Quién es más probable que diga 'serías perfecto o perfecta para una noche'?",
"¿Quién es más probable que se sonroje con 'te haría un oral ahora mismo'?",
"¿Quién es más probable que envíe un audio con sonidos de orgasmo como broma?",
"¿Quién es más probable que fantasee con un trío con dos personas del grupo?",
"¿Quién es más probable que diga 'pareces como si acabaras de tener un gran sexo'?",
"¿Quién es más probable que escriba 'quiero sentirte dentro de mí'?",
"¿Quién es más probable que envíe una foto después de la ducha con 'justo ahora'?",
"¿Quién es más probable que se sonroje cuando dicen 'tienes un trasero increíble'?",
"¿Quién es más probable que bese a alguien en el coche en un semáforo?",
"¿Quién es más probable que reaccione 😈 a una historia provocativa?",
"¿Quién es más probable que escriba 'ven, te espero desnudo o desnuda'?",
"¿Quién es más probable que mire las manos de alguien y piense 'las quiero sobre mí'?",
"¿Quién es más probable que envíe 'me estoy tocando pensando en ti'?",
"¿Quién es más probable que fantasee con sexo en la cocina de este piso?",
"¿Quién es más probable que diga 'te tomaría fuerte' en broma?",
"¿Quién es más probable que se sonroje por bromas sobre tamaño o profundidad?",
"¿Quién es más probable que escriba 'hagámoslo sin protección, confío en ti'?",
"¿Quién es más probable que envíe un video tocándose?",
"¿Quién es más probable que fantasee con un 69 con alguien aquí?",
"¿Quién es más probable que diga 'pareces una tentación hoy'?",
"¿Quién es más probable que escriba 'quiero que termines sobre mí'?",
"¿Quién es más probable que bese a alguien en el guardarropa de una fiesta?",
"¿Quién es más probable que escriba 'quiero que me tomes por detrás'?",
"¿Quién es más probable que se sonroje pensando que todos conocen sus fantasías?",
"¿Quién es más probable que escriba 'me vuelves loco o loca en la cama'?",
"¿Quién es más probable que fantasee con sexo en un ascensor?",
"¿Quién es más probable que escriba 'termino solo pensando en ti'?",
"¿Quién es más probable que diga 'hagámoslo sin decir una palabra'?",
"¿Quién es más probable que se sonroje cuando dicen 'parece que quieres sexo ahora mismo'?",
"¿Quién es más probable que escriba 'quiero probar todo contigo'?",
"¿Quién es más probable que envíe foto íntima diciendo 'califícalo'?",
"¿Quién es más probable que fantasee con BDSM con alguien del grupo?",
"¿Quién es más probable que diga 'te tendría ocupado toda la noche'?",
"¿Quién es más probable que se sonroje por una mordida juguetona en el cuello?",
"¿Quién es más probable que escriba 'quiero sentir tu lengua'?",
"¿Quién es más probable que envíe 'envía pechos o pene' al chat grupal?",
"¿Quién es más probable que fantasee con sexo en la ducha después de la fiesta?",
"¿Quién es más probable que diga 'serías perfecto para mis fantasías sucias'?",
"¿Quién es más probable que se sonroje con 'tendría sexo contigo aquí mismo'?",
"¿Quién es más probable que escriba 'repitamos, pero sin ropa'?",
"¿Quién es más probable que envíe 'te deseo tanto que ya no puedo más'?",
"¿Quién es más probable que se convierta en la leyenda de la noche después de este juego y beba más que todos?" 
],

fr:[
"Qui est le plus susceptible d'écrire à son ex à 3 heures du matin juste pour prendre des nouvelles ?",
"Qui est le plus susceptible de liker toutes les stories de son crush en une soirée ?",
"Qui est le plus susceptible de faire semblant d'être ivre pour embrasser quelqu'un ?",
"Qui est le plus susceptible d'oublier le prénom de quelqu'un après le premier baiser ?",
"Qui est le plus susceptible d'envoyer un mème au lieu de répondre à un flirt ?",
"Qui est le plus susceptible d'aller à un rendez-vous juste pour la nourriture gratuite ?",
"Qui est le plus susceptible d'écrire 'tu es canon 🔥' à 2h47 du matin ?",
"Qui est le plus susceptible de faire une capture d'écran d'un chat et de la montrer à tout le monde ?",
"Qui est le plus susceptible de regarder les stories de son crush dès le matin ?",
"Qui est le plus susceptible de liker un ancien post pour rappeler son existence ?",
"Qui est le plus susceptible de prétendre avoir froid pour recevoir un câlin ?",
"Qui est le plus susceptible d'envoyer trop de cœurs en une soirée ?",
"Qui est le plus susceptible de toucher une jambe sous la table et faire comme si de rien n'était ?",
"Qui est le plus susceptible d'écrire 'tu me manques' après un rendez-vous ?",
"Qui est le plus susceptible de mettre le statut 'c'est compliqué' en pensant à quelqu'un ?",
"Qui est le plus susceptible de sourire à son téléphone pour un seul message ?",
"Qui est le plus susceptible de faire semblant d'aimer la même musique que son crush ?",
"Qui est le plus susceptible d'écrire 'envoie une photo' sans raison ?",
"Qui est le plus susceptible de rougir après un long regard dans les yeux ?",
"Qui est le plus susceptible d'écrire 'bonne nuit ❤️' à quelqu'un qu'il connaît à peine ?",
"Qui est le plus susceptible d'embrasser quelqu'un dans un ascenseur ?",
"Qui est le plus susceptible de dire 'j'ai rêvé de toi' après un rendez-vous ?",
"Qui est le plus susceptible d'envoyer un message vocal drôle pour faire rire son crush ?",
"Qui est le plus susceptible de réagir 🔥 à une story provocante ?",
"Qui est le plus susceptible de flirter avec un barista ou un serveur pour des avantages ?",
"Qui est le plus susceptible d'écrire 'viens, je suis seul ou seule à la maison' après minuit ?",
"Qui est le plus susceptible d'envoyer une photo en sous-vêtements comme si de rien n'était ?",
"Qui est le plus susceptible de rougir à un compliment sur ses fesses ou sa poitrine ?",
"Qui est le plus susceptible d'embrasser quelqu'un dans les toilettes d'un bar ou d'un club ?",
"Qui est le plus susceptible d'écrire 'je veux te voir' à 4 heures du matin ?",
"Qui est le plus susceptible de faire semblant d'avoir fait tomber son téléphone pour se rapprocher ?",
"Qui est le plus susceptible de fantasmer sur un baiser avec quelqu'un du groupe ?",
"Qui est le plus susceptible d'envoyer un message vocal avec des gémissements pour plaisanter ?",
"Qui est le plus susceptible de dire 'tu as l'air de sortir d'un rapport' ?",
"Qui est le plus susceptible de mettre une photo de profil plus révélatrice que d'habitude ?",
"Qui est le plus susceptible d'écrire quelque chose de provocant dans un chat de groupe en étant ivre ?",
"Qui est le plus susceptible de regarder les lèvres de quelqu'un en pensant 'je les veux sur moi' ?",
"Qui est le plus susceptible d'embrasser quelqu'un sur un balcon pendant que les autres sont à l'intérieur ?",
"Qui est le plus susceptible d'envoyer un message intime à la mauvaise personne ?",
"Qui est le plus susceptible de rougir à la blague 'tu gémis fort ?' ",
"Qui est le plus susceptible d'écrire 'viens seulement en sous-vêtements' ?",
"Qui est le plus susceptible de fantasmer sur du sexe dans une voiture avec quelqu'un ici ?",
"Qui est le plus susceptible de dire pour plaisanter 'je coucherais avec toi' ?",
"Qui est le plus susceptible d'envoyer une photo intime pour un défi ?",
"Qui est le plus susceptible de rougir à un contact intime accidentel ?",
"Qui est le plus susceptible de publier une story en sous-vêtements avec 'nuit' ?",
"Qui est le plus susceptible d'écrire 'je veux t'entendre gémir mon nom' ?",
"Qui est le plus susceptible d'embrasser quelqu'un dans l'entrée d'un immeuble ?",
"Qui est le plus susceptible d'écrire à son ex 'j'ai fini en pensant à toi' ?",
"Qui est le plus susceptible de fantasmer sur le fait de rester seuls après la fête ?",
 "Qui est le plus susceptible de dire 'tu es la personne la plus sexy ici' dans le chat ?",
"Qui est le plus susceptible d'envoyer un sticker de baiser au lieu d'un vrai message ?",
"Qui est le plus susceptible de rougir parce que quelqu'un a dit 'tu es dangereusement sexy' ?",
"Qui est le plus susceptible d'écrire 'refaisons cette nuit' un an plus tard ?",
"Qui est le plus susceptible de flirter dans les commentaires du post de son crush ?",
"Qui est le plus susceptible de faire semblant d'aimer le sexe brutal pour ne pas blesser quelqu'un ?",
"Qui est le plus susceptible d'envoyer 'je te veux tellement que déjà…' ?",
"Qui est le plus susceptible de regarder du porno et penser 'ce serait génial avec quelqu'un ici' ?",
"Qui est le plus susceptible de dire 'tu serais parfait pour une nuit' ?",
"Qui est le plus susceptible de rougir à 'je te ferais un oral tout de suite' ?",
"Qui est le plus susceptible d'envoyer un message vocal avec des sons d'orgasme pour plaisanter ?",
"Qui est le plus susceptible de fantasmer sur un plan à trois avec deux personnes du groupe ?",
"Qui est le plus susceptible de dire 'tu as l'air de sortir d'un excellent sexe' ?",
"Qui est le plus susceptible d'écrire 'je veux te sentir en moi' ?",
"Qui est le plus susceptible d'envoyer une photo après la douche avec 'à l'instant' ?",
"Qui est le plus susceptible de rougir à 'tu as de superbes fesses' ?",
"Qui est le plus susceptible d'embrasser quelqu'un dans une voiture à un feu rouge ?",
"Qui est le plus susceptible de réagir 😈 à une story provocante ?",
"Qui est le plus susceptible d'écrire 'viens, je t'attends nu ou nue' ?",
"Qui est le plus susceptible de regarder les mains de quelqu'un et penser 'je les veux sur moi' ?",
"Qui est le plus susceptible d'envoyer 'je me touche en pensant à toi' ?",
"Qui est le plus susceptible de fantasmer sur du sexe dans la cuisine de cet appartement ?",
"Qui est le plus susceptible de dire 'je te prendrais fort' pour plaisanter ?",
"Qui est le plus susceptible de rougir aux blagues sur la taille ou la profondeur ?",
"Qui est le plus susceptible d'écrire 'faisons-le sans protection, je te fais confiance' ?",
"Qui est le plus susceptible d'envoyer une vidéo en train de se toucher ?",
"Qui est le plus susceptible de fantasmer sur un 69 avec quelqu'un ici ?",
"Qui est le plus susceptible de dire 'tu ressembles à une vraie tentation ce soir' ?",
"Qui est le plus susceptible d'écrire 'je veux que tu jouisses sur moi' ?",
"Qui est le plus susceptible d'embrasser quelqu'un dans le vestiaire d'une fête ?",
"Qui est le plus susceptible d'écrire 'je veux que tu me prennes par derrière' ?",
"Qui est le plus susceptible de rougir en pensant que tout le monde connaît ses fantasmes ?",
"Qui est le plus susceptible d'écrire 'tu me rends fou ou folle au lit' ?",
"Qui est le plus susceptible de fantasmer sur du sexe dans un ascenseur ?",
"Qui est le plus susceptible d'écrire 'je jouis rien qu'en pensant à toi' ?",
"Qui est le plus susceptible de dire 'faisons-le sans parler' ?",
"Qui est le plus susceptible de rougir à 'tu as l'air de vouloir du sexe maintenant' ?",
"Qui est le plus susceptible d'écrire 'je veux tout essayer avec toi' ?",
"Qui est le plus susceptible d'envoyer une photo intime avec 'note ça' ?",
"Qui est le plus susceptible de fantasmer sur du BDSM avec quelqu'un du groupe ?",
"Qui est le plus susceptible de dire 'je te garderais occupé toute la nuit' ?",
"Qui est le plus susceptible de rougir après une morsure légère dans le cou ?",
"Qui est le plus susceptible d'écrire 'je veux sentir ta langue' ?",
"Qui est le plus susceptible d'envoyer 'envoie seins ou sexe' dans le chat de groupe ?",
"Qui est le plus susceptible de fantasmer sur du sexe sous la douche après la fête ?",
"Qui est le plus susceptible de dire 'tu serais parfait pour mes fantasmes sales' ?",
"Qui est le plus susceptible de rougir à 'je coucherais avec toi ici même' ?",
"Qui est le plus susceptible d'écrire 'refaisons-le, mais sans vêtements' ?",
"Qui est le plus susceptible d'envoyer 'je te veux tellement que je n'en peux plus' ?",
"Qui est le plus susceptible de devenir la légende de la soirée après ce jeu et boire le plus ?" 
]

}
