const adultTruth = {

ru:[
"В какой позе тебе больше всего нравится кончать со мной?",
"Какая моя часть тела тебя заводит сильнее всего прямо сейчас?",
"Что я делаю языком такого, от чего у тебя всегда мурашки?",
"Как часто ты думаешь обо мне в сексуальном плане, когда меня нет рядом?",
"Какой мой стон или вздох во время секса тебе нравится больше всего?",
"Что бы ты хотел(а), чтобы я чаще делал(а) тебе руками?",
"Самая горячая фантазия обо мне, которую ты недавно вспоминал(а)?",
"В какой одежде (или без неё) я выгляжу для тебя максимально сексуально?",
"Что из моих движений в постели тебя доводит до предела?",
"Какой мой запах после секса тебе нравится больше всего?",
"Что бы ты хотел(а), чтобы я говорил(а) тебе во время близости?",
"Какой момент нашего секса ты бы пересматривал(а) снова и снова?",
"Что я делаю не так в оральном сексе (честно, но мягко)?",
"Как часто ты мастурбируешь, представляя именно нас двоих?",
"Какая поза кажется тебе самой интимной с нами?",
"Что из моих прикосновений тебя всегда заводит моментально?",
"Какой мой взгляд во время секса тебя особенно цепляет?",
"Что бы ты хотел(а) попробовать нового в нашей сексуальной жизни?",
"Какой мой оргазм тебе запомнился ярче всего и почему?",
"Что ты чувствуешь, когда я медленно раздеваю тебя?",
"Какой мой поцелуй в тело (не губы) тебе нравится больше всего?",
"Что из наших игр в постели ты бы хотел(а) повторять чаще?",
"Как часто ты вспоминаешь наш самый долгий секс?",
"Что бы ты хотел(а), чтобы я делал(а) дольше во время прелюдии?",
"Какой мой жест в постели тебя всегда приятно удивляет?",
"Что из моих слов во время секса тебя смущает, но одновременно заводит?",
"В какой момент ты чувствуешь себя самым желанным со мной?",
"Какой мой ритм движений тебе нравится больше всего?",
"Что бы ты хотел(а), чтобы я чаще целовал(а) на твоём теле?",
"Как часто ты фантазируешь о нас во время душа или ванны?",
"Что из моих ласк руками тебе нравится больше всего?",
"Какой мой вкус тебе запомнился сильнее всего?",
"Что бы ты хотел(а) услышать от меня прямо перед оргазмом?",
"Какой наш секс был самым неожиданным и горячим?",
"Что в моей реакции на твои прикосновения тебя заводит?",
"Какой мой вздох или стон ты бы хотел(а) слышать чаще?",
"Что бы ты изменил(а) в нашей прелюдии, чтобы было ещё лучше?",
"Как часто ты трогаешь себя, вспоминая наши поцелуи?",
"Какая часть прелюдии кажется тебе самой возбуждающей?",
"Что из моих движений бёдрами тебя всегда доводит?",
"Какой мой комплимент в постели тебе запомнился?",
"Что бы ты хотел(а), чтобы я делал(а) медленнее?",
"Как часто ты представляешь нас в разных местах дома?",
"Что в моих глазах во время секса тебя цепляет?",
"Какой мой поцелуй в шею, грудь или бедро самый чувствительный для тебя?",
"Что бы ты хотел(а) попробовать с завязанными глазами?",
"Какой наш секс утром тебе нравится больше всего?",
"Что из моих ласк ты бы хотел(а) длить вечно?",
"Как часто ты улыбаешься, вспоминая наш последний секс?",
"Что бы ты хотел(а) сказать мне в самый горячий момент прямо сейчас?"
],

en:[
"Which position do you enjoy finishing with me the most?",
"Which part of my body turns you on the most right now?",
"What do I do with my tongue that always gives you goosebumps?",
"How often do you think about me sexually when I'm not around?",
"Which of my moans or breaths during sex do you like the most?",
"What would you like me to do more often with my hands?",
"What is the hottest fantasy about me that you've thought about recently?",
"In what outfit (or without one) do I look the sexiest to you?",
"Which of my movements in bed drives you the craziest?",
"Which scent of mine after sex do you like the most?",
"What would you like me to say to you during intimacy?",
"Which moment from our sex would you replay over and over?",
"What do I do wrong during oral sex (honestly but gently)?",
"How often do you masturbate thinking specifically about the two of us?",
"Which position feels the most intimate for us?",
"Which of my touches turns you on instantly?",
"What look of mine during sex attracts you the most?",
"What would you like to try new in our sex life?",
"Which of my orgasms do you remember the most vividly and why?",
"What do you feel when I slowly undress you?",
"Which kiss on your body (not lips) do you enjoy the most?",
"What part of our bedroom games would you like to repeat more often?",
"How often do you remember our longest sex session?",
"What would you like me to do longer during foreplay?",
"Which gesture of mine in bed always pleasantly surprises you?",
"What words from me during sex make you shy but still turn you on?",
"When do you feel the most desired with me?",
"What rhythm of my movements do you enjoy the most?",
"Where on your body would you like me to kiss more often?",
"How often do you fantasize about us in the shower or bath?",
"Which of my touches with my hands do you like the most?",
"Which taste of mine do you remember the most?",
"What would you like to hear from me right before orgasm?",
"Which time we had sex was the most unexpected and hottest?",
"What about my reaction to your touch turns you on?",
"Which of my sighs or moans would you like to hear more often?",
"What would you change in our foreplay to make it even better?",
"How often do you touch yourself remembering our kisses?",
"Which part of foreplay excites you the most?",
"Which of my hip movements drives you crazy?",
"Which compliment from me in bed stayed in your memory?",
"What would you like me to do more slowly?",
"How often do you imagine us in different places around the house?",
"What about my eyes during sex attracts you the most?",
"Which kiss of mine on your neck, chest, or thigh feels the most sensitive?",
"What would you like to try with your eyes closed or blindfolded?",
"Which kind of morning sex between us do you enjoy the most?",
"Which of my touches would you want to last forever?",
"How often do you smile remembering the last time we had sex?",
"What would you like to say to me in the hottest moment right now?"
],

es:[
"¿En qué posición te gusta más terminar conmigo?",
"¿Qué parte de mi cuerpo te excita más ahora mismo?",
"¿Qué hago con mi lengua que siempre te provoca escalofríos?",
"¿Con qué frecuencia piensas en mí sexualmente cuando no estoy cerca?",
"¿Qué gemido o suspiro mío durante el sexo te gusta más?",
"¿Qué te gustaría que hiciera más a menudo con mis manos?",
"¿Cuál es la fantasía más caliente sobre mí que recuerdas recientemente?",
"¿Con qué ropa (o sin ella) me ves más sexy?",
"¿Qué movimiento mío en la cama te vuelve más loco?",
"¿Qué olor mío después del sexo te gusta más?",
"¿Qué te gustaría que te dijera durante la intimidad?",
"¿Qué momento de nuestro sexo repetirías una y otra vez?",
"¿Qué hago mal en el sexo oral (honestamente pero con cariño)?",
"¿Con qué frecuencia te masturbas pensando en nosotros dos?",
"¿Qué posición te parece la más íntima para nosotros?",
"¿Qué caricia mía te excita al instante?",
"¿Qué mirada mía durante el sexo te vuelve loco?",
"¿Qué te gustaría probar nuevo en nuestra vida sexual?",
"¿Qué orgasmo mío recuerdas con más intensidad?",
"¿Qué sientes cuando te desnudo lentamente?",
"¿Qué beso mío en tu cuerpo te gusta más?",
"¿Qué parte de nuestros juegos en la cama repetirías más?",
"¿Con qué frecuencia recuerdas nuestro sexo más largo?",
"¿Qué te gustaría que hiciera más tiempo durante los preliminares?",
"¿Qué gesto mío en la cama siempre te sorprende?",
"¿Qué palabras mías durante el sexo te avergüenzan pero te excitan?",
"¿Cuándo te sientes más deseado(a) conmigo?",
"¿Qué ritmo de mis movimientos te gusta más?",
"¿Dónde en tu cuerpo te gustaría que te besara más?",
"¿Con qué frecuencia fantaseas con nosotros en la ducha o el baño?",
"¿Qué caricia mía con las manos te gusta más?",
"¿Qué sabor mío recuerdas más?",
"¿Qué te gustaría escuchar de mí justo antes del orgasmo?",
"¿Cuál de nuestros encuentros fue el más inesperado y apasionado?",
"¿Qué de mi reacción a tus caricias te excita?",
"¿Qué suspiro o gemido mío quieres oír más?",
"¿Qué cambiarías en nuestros preliminares para que sean mejores?",
"¿Con qué frecuencia te tocas pensando en nuestros besos?",
"¿Qué parte de los preliminares te excita más?",
"¿Qué movimiento de mis caderas te vuelve loco?",
"¿Qué cumplido mío en la cama recuerdas?",
"¿Qué te gustaría que hiciera más despacio?",
"¿Con qué frecuencia imaginas que estamos en diferentes lugares de la casa?",
"¿Qué de mis ojos durante el sexo te atrae?",
"¿Qué beso mío en tu cuello, pecho o muslo es más sensible para ti?",
"¿Qué te gustaría probar con los ojos vendados?",
"¿Qué tipo de sexo por la mañana te gusta más?",
"¿Qué caricia mía te gustaría que durara para siempre?",
"¿Con qué frecuencia sonríes recordando nuestro último sexo?",
"¿Qué te gustaría decirme en el momento más caliente ahora mismo?"
],

fr:[
"Dans quelle position préfères-tu finir avec moi ?",
"Quelle partie de mon corps t'excite le plus en ce moment ?",
"Que fais-je avec ma langue qui te donne toujours des frissons ?",
"À quelle fréquence penses-tu à moi sexuellement quand je ne suis pas là ?",
"Quel gémissement ou soupir de ma part pendant le sexe préfères-tu ?",
"Que voudrais-tu que je fasse plus souvent avec mes mains ?",
"Quelle est la fantasme la plus chaude que tu as eue récemment à propos de moi ?",
"Dans quelle tenue (ou sans) me trouves-tu le plus sexy ?",
"Quel mouvement de ma part au lit te fait perdre le contrôle ?",
"Quelle odeur de moi après le sexe préfères-tu ?",
"Qu'aimerais-tu que je te dise pendant l'intimité ?",
"Quel moment de notre sexe aimerais-tu revivre encore et encore ?",
"Que fais-je mal pendant le sexe oral (honnêtement mais doucement) ?",
"À quelle fréquence te masturbes-tu en pensant à nous deux ?",
"Quelle position te semble la plus intime pour nous ?",
"Quelle de mes caresses t'excite immédiatement ?",
"Quel regard de ma part pendant le sexe te touche le plus ?",
"Qu'aimerais-tu essayer de nouveau dans notre vie sexuelle ?",
"Quel de mes orgasmes te reste le plus en mémoire ?",
"Que ressens-tu quand je te déshabille lentement ?",
"Quel baiser de ma part sur ton corps préfères-tu ?",
"Quelle partie de nos jeux au lit voudrais-tu répéter plus souvent ?",
"À quelle fréquence repenses-tu à notre plus long moment ensemble ?",
"Que voudrais-tu que je fasse plus longtemps pendant les préliminaires ?",
"Quel geste de ma part au lit te surprend toujours agréablement ?",
"Quelles paroles de moi pendant le sexe te gênent mais t'excitent ?",
"Quand te sens-tu le plus désiré(e) avec moi ?",
"Quel rythme de mes mouvements préfères-tu ?",
"Où sur ton corps aimerais-tu que je t'embrasse plus souvent ?",
"À quelle fréquence fantasmes-tu sur nous sous la douche ou dans le bain ?",
"Quelle de mes caresses avec les mains préfères-tu ?",
"Quel goût de moi te reste le plus en mémoire ?",
"Qu'aimerais-tu entendre de moi juste avant l'orgasme ?",
"Quel moment entre nous était le plus inattendu et le plus intense ?",
"Qu'est-ce qui dans ma réaction à tes caresses t'excite ?",
"Quel soupir ou gémissement de moi voudrais-tu entendre plus souvent ?",
"Que changerais-tu dans nos préliminaires pour que ce soit encore mieux ?",
"À quelle fréquence te touches-tu en pensant à nos baisers ?",
"Quelle partie des préliminaires t'excite le plus ?",
"Quel mouvement de mes hanches te fait perdre la tête ?",
"Quel compliment de ma part au lit te reste en mémoire ?",
"Que voudrais-tu que je fasse plus lentement ?",
"À quelle fréquence imagines-tu que nous sommes dans différents endroits de la maison ?",
"Qu'est-ce qui dans mes yeux pendant le sexe t'attire ?",
"Quel baiser de ma part sur ton cou, ta poitrine ou ta cuisse est le plus sensible ?",
"Qu'aimerais-tu essayer avec les yeux bandés ?",
"Quel sexe du matin préfères-tu entre nous ?",
"Quelle de mes caresses aimerais-tu qu'elle dure pour toujours ?",
"À quelle fréquence souris-tu en repensant à notre dernier moment intime ?",
"Que voudrais-tu me dire dans le moment le plus intense maintenant ?"
]

}

const adultDare = {

ru:[
"Сделай мне очень медленный и чувственный массаж всего тела 3 минуты.",
"Поцелуй меня в 8 разных мест ниже шеи медленно.",
"Сними с меня одну вещь очень медленно, глядя в глаза.",
"Сделай мне оральные ласки ровно 90 секунд и остановись.",
"Прошепчи мне на ухо 5 самых горячих фраз о том, что хочешь со мной.",
"Станцуй для меня эротично в нижнем белье под мою песню.",
"Позволь мне завязать тебе глаза и ласкать тебя пальцами 2 минуты.",
"Сделай мне минет или куни в очень медленном темпе 60 секунд.",
"Напиши «хочу тебя» помадой на своём теле и покажи.",
"Сделай селфи, где ты целуешь мою грудь или живот.",
"Потанцуй на мне сверху в белье 60 секунд.",
"Сделай мне засос на шее или груди.",
"Позволь мне шлёпнуть тебя по попе 10 раз игриво.",
"Съешь что-то сладкое с моего живота или бёдер без рук.",
"Сделай мне массаж груди или ягодиц с поцелуями.",
"Произнеси моё имя стонательно 5 раз.",
"Позволь мне ласкать тебя пальцами, пока ты не попросишь продолжения.",
"Сделай позу 69 ровно 60 секунд.",
"Запиши голосовое с возбуждённым «хочу тебя сейчас».",
"Сделай мне оральные ласки через ткань белья 30 секунд.",
"Позволь мне написать тебе что-то горячее на внутренней стороне бедра.",
"Сделай мне комплимент каждой части моего тела ниже пояса.",
"Потанцуй стриптиз до гола или почти до гола.",
"Дразни меня руками, доведи до края 2 раза и остановись.",
"Покажи, как ты себя трогаешь, глядя мне в глаза.",
"Сделай глубокий поцелуй с языком 90 секунд без остановки.",
"Позволь мне ласкать тебя языком по телу 2 минуты.",
"Сделай селфи наших тел в обнимку.",
"Произнеси «я твоя» или «я твой» максимально сексуально.",
"Сделай мне массаж попы с поцелуями.",
"Позволь мне завязать тебе руки шарфом и ласкать тебя 2 минуты.",
"Сделай мне оральные ласки с кубиком льда во рту.",
"Напиши в заметки самое горячее желание и зачитай вслух.",
"Сядь на меня сверху 45 секунд.",
"Покажи свою любимую позу и объясни, почему она тебе нравится.",
"Сделай мне засос на внутренней стороне бедра.",
"Позволь мне кончить на твою грудь или живот.",
"Запиши голосовое с имитацией стонов.",
"Сделай мне оральные ласки с большим количеством слюны.",
"Потанцуй тверк голышом или в стрингах.",
"Позволь мне шлёпнуть тебя по бёдрам и попе 15 раз.",
"Дразни меня ласками, но не давай кончить 3 минуты.",
"Напиши моё имя языком на своём животе и покажи.",
"Сделай мне комплимент моим интимным частям максимально откровенно.",
"Позволь мне ласкать тебя пальцами до оргазма.",
"Сделай селфи после — растрёпанные волосы и покрасневшая кожа.",
"Произнеси самую горячую фразу, которую можешь придумать.",
"Сделай мне оральные ласки с вибрацией.",
"Позволь мне ласкать тебя пальцами медленно и глубоко.",
"Закончи игру тем, что мы занимаемся сексом в любимой позе."
],

en:[
"Give me a very slow and sensual full body massage for 3 minutes.",
"Kiss me slowly in 8 different places below the neck.",
"Take one piece of clothing off me very slowly while looking into my eyes.",
"Give me oral pleasure for exactly 90 seconds and then stop.",
"Whisper in my ear 5 of the hottest things you want to do with me.",
"Dance for me erotically in your underwear to my song.",
"Let me blindfold you and touch you with my fingers for 2 minutes.",
"Give me oral pleasure very slowly for 60 seconds.",
"Write 'I want you' on your body with lipstick and show me.",
"Take a selfie where you're kissing my chest or stomach.",
"Grind on me while sitting on top for 60 seconds.",
"Give me a small hickey on my neck or chest.",
"Let me playfully slap your butt 10 times.",
"Eat something sweet off my stomach or thighs without using your hands.",
"Give me a massage of my chest or butt with kisses.",
"Moan my name 5 times.",
"Let me pleasure you with my fingers until you ask for more.",
"Do the 69 position for exactly 60 seconds.",
"Send a voice message saying 'I want you now' in a very excited tone.",
"Give me oral pleasure through underwear for 30 seconds.",
"Let me write something naughty on the inside of your thigh.",
"Give a compliment to every part of my body below the waist.",
"Do a striptease until you're naked or almost naked.",
"Tease me with your hands and bring me close twice but stop.",
"Show me how you touch yourself while looking into my eyes.",
"Kiss me deeply with tongue for 90 seconds without stopping.",
"Let me tease your body with my tongue for 2 minutes.",
"Take a selfie of our bodies hugging.",
"Say 'I'm yours' in the sexiest way you can.",
"Give me a butt massage with kisses.",
"Let me tie your hands with a scarf and tease you for 2 minutes.",
"Give me oral pleasure with an ice cube in your mouth.",
"Write your hottest desire in notes and read it out loud.",
"Sit on my face for 45 seconds.",
"Show your favorite position and explain why you like it.",
"Give me a hickey on the inside of my thigh.",
"Let me finish on your chest or stomach.",
"Send a voice message imitating moans.",
"Give me oral pleasure with a lot of saliva.",
"Twerk naked or in a thong.",
"Let me slap your thighs and butt 15 times playfully.",
"Tease me without letting me finish for 3 minutes.",
"Spell my name with your tongue on your stomach.",
"Give a very honest compliment about my genitals.",
"Let me pleasure you with my fingers until orgasm.",
"Take an after selfie — messy hair and flushed skin.",
"Say the hottest phrase you can think of.",
"Give me oral pleasure using vibration if there is a toy.",
"Let me pleasure you slowly and deeply with my fingers.",
"Finish the game by having sex in your favorite position."
],

es:[
"Dame un masaje muy lento y sensual por todo el cuerpo durante 3 minutos.",
"Bésame lentamente en 8 lugares diferentes debajo del cuello.",
"Quítame una prenda muy lentamente mirándome a los ojos.",
"Dame placer oral durante exactamente 90 segundos y detente.",
"Susúrrame al oído 5 de las frases más calientes que quieras hacer conmigo.",
"Baila para mí de forma erótica en ropa interior con mi canción.",
"Déjame vendarte los ojos y acariciarte con mis dedos durante 2 minutos.",
"Dame placer oral muy lentamente durante 60 segundos.",
"Escribe 'te deseo' con lápiz labial en tu cuerpo y muéstralo.",
"Haz un selfie besando mi pecho o mi vientre.",
"Muévete sobre mí sensualmente durante 60 segundos.",
"Hazme un pequeño chupetón en el cuello o el pecho.",
"Déjame darte 10 palmadas juguetonas en el trasero.",
"Come algo dulce de mi vientre o muslos sin usar las manos.",
"Dame un masaje en el pecho o las nalgas con besos.",
"Gime mi nombre 5 veces.",
"Déjame acariciarte con los dedos hasta que pidas más.",
"Hagamos la posición 69 durante 60 segundos.",
"Envíame un audio diciendo 'te quiero ahora' con mucha excitación.",
"Dame placer oral a través de la ropa interior durante 30 segundos.",
"Déjame escribir algo picante en tu muslo interno.",
"Halaga cada parte de mi cuerpo debajo de la cintura.",
"Haz un striptease hasta quedar desnudo(a) o casi.",
"Provócame con tus manos hasta el límite dos veces y detente.",
"Muéstrame cómo te tocas mirándome a los ojos.",
"Bésame profundamente con lengua durante 90 segundos.",
"Déjame recorrer tu cuerpo con mi lengua durante 2 minutos.",
"Haz un selfie de nuestros cuerpos abrazados.",
"Di 'soy tuyo o tuya' de la forma más sexy.",
"Dame un masaje en las nalgas con besos.",
"Déjame atarte las manos con una bufanda y provocarte 2 minutos.",
"Dame placer oral con un cubito de hielo en la boca.",
"Escribe tu deseo más caliente en notas y léelo.",
"Siéntate sobre mí durante 45 segundos.",
"Muestra tu posición favorita y explica por qué.",
"Hazme un chupetón en la parte interna del muslo.",
"Déjame terminar sobre tu pecho o vientre.",
"Envíame un audio imitando gemidos.",
"Dame placer oral con mucha saliva.",
"Baila twerk desnudo o en tanga.",
"Déjame darte 15 palmadas juguetonas en muslos y trasero.",
"Provócame sin dejarme terminar durante 3 minutos.",
"Escribe mi nombre con la lengua sobre tu vientre.",
"Dame un cumplido muy directo sobre mis genitales.",
"Déjame acariciarte con los dedos hasta el orgasmo.",
"Haz un selfie después — cabello despeinado y piel enrojecida.",
"Di la frase más caliente que puedas imaginar.",
"Dame placer oral usando vibración si hay juguete.",
"Déjame estimularte lentamente con los dedos.",
"Termina el juego teniendo sexo en vuestra posición favorita."
],

fr:[
"Fais-moi un massage très lent et sensuel de tout le corps pendant 3 minutes.",
"Embrasse-moi lentement à 8 endroits différents sous le cou.",
"Enlève un de mes vêtements très lentement en me regardant dans les yeux.",
"Donne-moi du plaisir oral pendant exactement 90 secondes puis arrête.",
"Chuchote-moi à l'oreille 5 des choses les plus chaudes que tu veux me faire.",
"Danse pour moi de manière érotique en sous-vêtements sur ma chanson.",
"Laisse-moi te bander les yeux et te caresser avec mes doigts pendant 2 minutes.",
"Donne-moi du plaisir oral très lentement pendant 60 secondes.",
"Écris 'je te veux' sur ton corps avec du rouge à lèvres et montre-le.",
"Fais un selfie en embrassant ma poitrine ou mon ventre.",
"Frotte-toi sur moi pendant 60 secondes.",
"Fais-moi un petit suçon dans le cou ou sur la poitrine.",
"Laisse-moi te donner 10 tapes joueuses sur les fesses.",
"Mange quelque chose de sucré sur mon ventre ou mes cuisses sans les mains.",
"Fais-moi un massage de la poitrine ou des fesses avec des baisers.",
"Gémis mon nom 5 fois.",
"Laisse-moi te caresser avec mes doigts jusqu'à ce que tu en veuilles plus.",
"Fais la position 69 pendant 60 secondes.",
"Envoie un message vocal disant 'je te veux maintenant'.",
"Donne-moi du plaisir oral à travers le tissu des sous-vêtements pendant 30 secondes.",
"Laisse-moi écrire quelque chose de chaud sur l'intérieur de ta cuisse.",
"Fais un compliment à chaque partie de mon corps sous la taille.",
"Fais un striptease jusqu'à être nu(e) ou presque.",
"Taquine-moi avec tes mains et amène-moi au bord deux fois puis arrête.",
"Montre comment tu te touches en me regardant dans les yeux.",
"Embrasse-moi profondément avec la langue pendant 90 secondes.",
"Laisse-moi parcourir ton corps avec ma langue pendant 2 minutes.",
"Fais un selfie de nos corps enlacés.",
"Dis 'je suis à toi' de la façon la plus sexy.",
"Fais-moi un massage des fesses avec des baisers.",
"Laisse-moi attacher tes mains avec une écharpe et te taquiner 2 minutes.",
"Donne-moi du plaisir oral avec un glaçon dans la bouche.",
"Écris ton désir le plus chaud dans les notes et lis-le.",
"Assieds-toi sur moi pendant 45 secondes.",
"Montre ta position préférée et explique pourquoi.",
"Fais-moi un suçon à l'intérieur de la cuisse.",
"Laisse-moi finir sur ta poitrine ou ton ventre.",
"Envoie un message vocal avec des gémissements.",
"Donne-moi du plaisir oral avec beaucoup de salive.",
"Twerk nu(e) ou en string.",
"Laisse-moi te donner 15 tapes joueuses sur les cuisses et les fesses.",
"Taquine-moi sans me laisser finir pendant 3 minutes.",
"Écris mon nom avec ta langue sur ton ventre.",
"Fais un compliment très direct sur mes parties intimes.",
"Laisse-moi te caresser avec les doigts jusqu'à l'orgasme.",
"Fais un selfie après — cheveux en bataille et peau rouge.",
"Dis la phrase la plus chaude que tu peux imaginer.",
"Donne-moi du plaisir oral avec vibration si un jouet est disponible.",
"Laisse-moi te stimuler lentement avec mes doigts.",
"Termine le jeu en faisant l'amour dans votre position préférée."
]

}
