const coupleTruth = {

ru:[
"Какой мой привычный жест, когда я нервничаю, ты замечаешь первым?",
"Что в наших отношениях за эти годы изменилось в лучшую сторону?",
"Какой наш совместный день ты бы пережил(а) заново без изменений?",
"Что я делаю по утрам такого, что тебя всегда умиляет?",
"Какой мой «домашний» вид (в пижаме/без макияжа) тебе нравится больше всего?",
"Что ты тайно копируешь у меня в поведении?",
"Какой запах от меня ассоциируется у тебя с домом?",
"В какой момент ты понял(а), что мы надолго?",
"Что я говорю во сне самое смешное или милое?",
"Какой наш ритуал (типа «чай перед сном») ты ценишь больше всего?",
"Что в моей походке изменилось с тех пор, как мы вместе?",
"Какой мой комплимент тебе запомнился на всю жизнь?",
"Что ты любишь в том, как я тебя обнимаю?",
"Какой наш «внутренний» мем ты вспоминаешь чаще всего?",
"Что я делаю, когда думаю, что ты не видишь, и это тебя трогает?",
"Какой подарок от меня был самым неожиданным и приятным?",
"Что в наших ссорах ты всегда ценишь (как мы миримся)?",
"Какой мой голосовой тон моментально тебя успокаивает?",
"Что ты хотел(а) бы, чтобы я чаще говорил(а) тебе?",
"Какой наш совместный провал стал самой смешной историей?",
"Что в моей улыбке тебя цепляет даже спустя годы?",
"Какой мой «пьяный» танец тебе нравится больше всего?",
"Что ты чувствуешь, когда я беру тебя за руку на улице?",
"Какой наш отпуск/поездка был идеальным?",
"Что я ем такого странного, но ты уже привык(ла) и любишь?",
"Какой мой жест заботы ты считаешь самым искренним?",
"Что в нас двоих делает нас «не такой парой, как все»?",
"Какой мой взгляд ты любишь ловить на себе?",
"Что ты скрываешь от меня из милой ревности?",
"Какой наш «ленивый» день — твой любимый формат?",
"Что я делаю в постели (сонной) такого милого?",
"Какой мой текст/голосовое тебе всегда поднимает настроение?",
"Что ты хотел(а) бы изменить в наших привычках вместе?",
"Какой момент «я люблю тебя» был самым неожиданным?",
"Что в моей одежде ты тайно крадёшь носить?",
"Какой наш праздник мы отмечаем лучше всех?",
"Что я говорю, когда злюсь, но ты знаешь — это не всерьёз?",
"Какой мой талант ты гордишься больше всего?",
"Что ты чувствуешь, когда мы долго не видимся?",
"Какой наш «секретный» сигнал друг другу?",
"Что в моих прикосновениях тебя всегда заводит (не сексуально, а нежно)?",
"Какой мой недостаток ты уже считаешь частью любви?",
"Что ты хотел(а) бы чаще делать вместе по вечерам?",
"Какой наш разговор ночью был самым глубоким?",
"Что я делаю, когда ты грустишь, и это всегда работает?",
"Какой мой «домашний» аромат ты бы взял(а) с собой в командировку?",
"Что в наших планах на будущее тебя больше всего греет?",
"Какой мой смех ты можешь узнать из тысячи?",
"Что ты ценишь в том, как мы выросли вместе?",
"Если бы ты мог(ла) сказать мне одну вещь, которую редко говоришь — что бы это было?"
],

en:[
"What habit or gesture of mine do you notice first when I'm nervous?",
"What has changed for the better in our relationship over the years?",
"Which day we spent together would you relive exactly the same?",
"What do I do in the mornings that always melts your heart?",
"Which of my 'at-home' looks (in pajamas/no makeup) do you like the most?",
"What habit of mine have you secretly started copying?",
"What scent of mine reminds you of home?",
"When did you realize that we were in it for the long run?",
"What funny or cute things do I say in my sleep?",
"Which of our little rituals (like tea before bed) do you value the most?",
"What has changed about the way I walk since we've been together?",
"Which compliment from me has stayed with you forever?",
"What do you love about the way I hug you?",
"Which of our inside jokes do you remember the most?",
"What do I do when I think you're not looking that secretly touches you?",
"Which gift from me was the most unexpected and sweet?",
"What do you appreciate even during our arguments (like how we make up)?",
"What tone of my voice calms you down instantly?",
"What would you like me to say to you more often?",
"Which of our shared failures turned into the funniest story?",
"What about my smile still catches you even after all these years?",
"Which of my 'tipsy' dances do you like the most?",
"What do you feel when I take your hand in public?",
"Which trip or vacation of ours felt perfect?",
"What strange food do I eat that you've gotten used to and even like now?",
"Which caring gesture from me feels the most genuine?",
"What makes us feel like 'not just any couple'?",
"What kind of look from me do you love catching?",
"What do you secretly hide from me out of cute jealousy?",
"What kind of 'lazy day together' is your favorite?",
"What cute thing do I do when I'm sleepy in bed?",
"Which message or voice note from me always lifts your mood?",
"What habit of ours would you like to change together?",
"Which 'I love you' moment surprised you the most?",
"What piece of my clothing do you secretly steal to wear?",
"Which holiday do we celebrate the best together?",
"What do I say when I'm angry but you know I don't really mean it?",
"Which of my talents are you most proud of?",
"What do you feel when we haven't seen each other for a long time?",
"What is our little 'secret signal' to each other?",
"What about my touch always excites you (not sexually, but tenderly)?",
"Which of my flaws have you already accepted as part of love?",
"What would you like us to do together more often in the evenings?",
"Which late-night conversation of ours was the deepest?",
"What do I do when you're sad that always works?",
"Which of my 'home scents' would you take with you on a business trip?",
"What part of our future plans warms your heart the most?",
"Which of my laughs could you recognize out of a thousand?",
"What do you appreciate about how we've grown together?",
"If you could tell me one thing you rarely say — what would it be?"
],

es:[
"¿Qué gesto mío notas primero cuando estoy nervioso(a)?",
"¿Qué ha cambiado para mejor en nuestra relación con los años?",
"¿Qué día que pasamos juntos te gustaría volver a vivir exactamente igual?",
"¿Qué hago por las mañanas que siempre te enternece?",
"¿Cuál de mis looks de casa (en pijama/sin maquillaje) te gusta más?",
"¿Qué hábito mío has empezado a copiar en secreto?",
"¿Qué olor mío te recuerda a casa?",
"¿En qué momento entendiste que lo nuestro iba en serio?",
"¿Qué digo mientras duermo que te parece más gracioso o tierno?",
"¿Cuál de nuestros pequeños rituales (como el té antes de dormir) valoras más?",
"¿Qué ha cambiado en mi forma de caminar desde que estamos juntos?",
"¿Qué cumplido mío recuerdas para siempre?",
"¿Qué te gusta de la forma en que te abrazo?",
"¿Cuál de nuestros chistes internos recuerdas más?",
"¿Qué hago cuando creo que no me ves que en secreto te conmueve?",
"¿Cuál fue el regalo mío más inesperado y bonito?",
"¿Qué valoras incluso en nuestras discusiones (como cuando hacemos las paces)?",
"¿Qué tono de mi voz te calma al instante?",
"¿Qué te gustaría que te dijera más a menudo?",
"¿Qué fracaso nuestro terminó siendo la historia más divertida?",
"¿Qué de mi sonrisa te sigue atrapando incluso después de años?",
"¿Cuál de mis bailes cuando estoy un poco borracho(a) te gusta más?",
"¿Qué sientes cuando te tomo de la mano en la calle?",
"¿Qué viaje o vacaciones nuestras fueron perfectas?",
"¿Qué comida rara mía ya aceptaste e incluso te gusta?",
"¿Qué gesto de cariño mío te parece el más sincero?",
"¿Qué hace que nosotros seamos una pareja diferente?",
"¿Qué mirada mía te gusta encontrar en ti?",
"¿Qué celito tierno escondes de mí?",
"¿Qué tipo de día perezoso juntos es tu favorito?",
"¿Qué cosa tierna hago cuando estoy medio dormido(a) en la cama?",
"¿Qué mensaje o audio mío siempre te anima?",
"¿Qué hábito nuestro te gustaría cambiar juntos?",
"¿Qué momento de 'te quiero' fue el más inesperado?",
"¿Qué prenda mía sueles robar para ponértela?",
"¿Qué celebración hacemos mejor que nadie?",
"¿Qué digo cuando estoy enfadado(a) pero sabes que no es en serio?",
"¿De qué talento mío te sientes más orgulloso(a)?",
"¿Qué sientes cuando pasamos mucho tiempo sin vernos?",
"¿Cuál es nuestra señal secreta?",
"¿Qué de mis caricias siempre te enciende (de forma tierna, no sexual)?",
"¿Qué defecto mío ya forma parte del amor para ti?",
"¿Qué te gustaría que hiciéramos más juntos por las noches?",
"¿Cuál de nuestras conversaciones nocturnas fue la más profunda?",
"¿Qué hago cuando estás triste que siempre funciona?",
"¿Qué aroma mío de casa te llevarías en un viaje de trabajo?",
"¿Qué parte de nuestros planes de futuro te da más calor al corazón?",
"¿Qué risa mía reconocerías entre mil?",
"¿Qué valoras de cómo hemos crecido juntos?",
"Si pudieras decirme algo que rara vez dices — ¿qué sería?"
],

fr:[
"Quel geste chez moi remarques-tu en premier quand je suis nerveux(se) ?",
"Qu'est-ce qui a changé pour le mieux dans notre relation au fil des années ?",
"Quelle journée passée ensemble aimerais-tu revivre exactement de la même façon ?",
"Que fais-je le matin qui te fait toujours fondre ?",
"Quel de mes looks à la maison (en pyjama/sans maquillage) préfères-tu ?",
"Quelle habitude de moi as-tu secrètement commencé à copier ?",
"Quelle odeur de moi te rappelle la maison ?",
"À quel moment as-tu compris que nous étions faits pour durer ?",
"Qu'est-ce que je dis en dormant qui est le plus drôle ou mignon ?",
"Lequel de nos petits rituels (comme le thé avant de dormir) apprécies-tu le plus ?",
"Qu'est-ce qui a changé dans ma façon de marcher depuis qu'on est ensemble ?",
"Quel compliment de moi n'oublieras-tu jamais ?",
"Qu'aimes-tu dans la façon dont je te serre dans mes bras ?",
"Lequel de nos mèmes ou blagues internes te fait le plus sourire ?",
"Que fais-je quand je pense que tu ne regardes pas et qui te touche en secret ?",
"Quel cadeau de moi t'a le plus surpris et fait plaisir ?",
"Qu'apprécies-tu même dans nos disputes (comme notre façon de nous réconcilier) ?",
"Quel ton de ma voix te calme immédiatement ?",
"Qu'aimerais-tu que je te dise plus souvent ?",
"Quel échec vécu ensemble est devenu l'histoire la plus drôle ?",
"Qu'est-ce qui dans mon sourire t'attire encore après toutes ces années ?",
"Lequel de mes danses quand je suis un peu ivre préfères-tu ?",
"Que ressens-tu quand je te prends la main dans la rue ?",
"Quel voyage ou quelles vacances ensemble étaient parfaits ?",
"Quelle nourriture étrange que je mange as-tu fini par aimer ?",
"Quel geste d'attention de ma part te semble le plus sincère ?",
"Qu'est-ce qui fait que nous sommes un couple différent des autres ?",
"Quel regard de moi aimes-tu surprendre ?",
"Quelle petite jalousie mignonne caches-tu de moi ?",
"Quel type de journée paresseuse ensemble préfères-tu ?",
"Quelle chose mignonne fais-je quand je suis à moitié endormi(e) au lit ?",
"Quel message ou audio de moi te remonte toujours le moral ?",
"Quelle habitude de nous deux aimerais-tu changer ?",
"Quel moment où j'ai dit 'je t'aime' t'a le plus surpris ?",
"Quel vêtement à moi aimes-tu secrètement porter ?",
"Quelle fête célébrons-nous mieux que tout le monde ?",
"Que dis-je quand je suis en colère mais que tu sais que ce n'est pas sérieux ?",
"De quel talent chez moi es-tu le plus fier/fière ?",
"Que ressens-tu quand on ne se voit pas longtemps ?",
"Quel est notre signal secret ?",
"Qu'est-ce qui dans mes gestes tendres t'émeut toujours (pas sexuel, mais affectueux) ?",
"Quel défaut chez moi fais-tu déjà partie de l'amour ?",
"Qu'aimerais-tu que nous fassions plus souvent ensemble le soir ?",
"Quelle conversation nocturne entre nous était la plus profonde ?",
"Que fais-je quand tu es triste qui fonctionne toujours ?",
"Quelle odeur de moi à la maison emporterais-tu en voyage ?",
"Quelle partie de nos projets d'avenir te réchauffe le cœur ?",
"Quel rire de moi reconnaîtrais-tu entre mille ?",
"Qu'apprécies-tu dans la façon dont nous avons grandi ensemble ?",
"Si tu pouvais me dire une chose que tu dis rarement — quelle serait-elle ?"
]

}

const coupleDare = {

ru:[
"Обними меня на 10 секунд",
"Поцелуй меня"
],

en:[
"Hug me for 10 seconds",
"Kiss me"
],

es:[
"Abrázame durante 10 segundos",
"Bésame"
],

fr:[
"Fais-moi un câlin pendant 10 secondes",
"Embrasse-moi"
]

}
