const coupleTruth = {

ru:[
"Какой мой привычный жест, когда я нервничаю, ты замечаешь первым?",
"Что в наших отношениях за эти годы изменилось в лучшую сторону?",
"Какой наш совместный день ты бы пережил(а) заново без изменений?",
"Что я делаю по утрам такого, что тебя всегда умиляет?",
"Какой мой «домашний» вид (в пижаме/без макияжа) тебе нравится больше всего?",
"Что ты тайно копируешь у меня в поведении?",
"Какой запах от меня ассоциируется у тебя с домом?",
"В какой момент ты понял(а), что мы надолго?",
"Что я говорю во сне самое смешное или милое?",
"Какой наш ритуал (типа «чай перед сном») ты ценишь больше всего?",
"Что в моей походке изменилось с тех пор, как мы вместе?",
"Какой мой комплимент тебе запомнился на всю жизнь?",
"Что ты любишь в том, как я тебя обнимаю?",
"Какой наш «внутренний» мем ты вспоминаешь чаще всего?",
"Что я делаю, когда думаю, что ты не видишь, и это тебя трогает?",
"Какой подарок от меня был самым неожиданным и приятным?",
"Что в наших ссорах ты всегда ценишь (как мы миримся)?",
"Какой мой голосовой тон моментально тебя успокаивает?",
"Что ты хотел(а) бы, чтобы я чаще говорил(а) тебе?",
"Какой наш совместный провал стал самой смешной историей?",
"Что в моей улыбке тебя цепляет даже спустя годы?",
"Какой мой «пьяный» танец тебе нравится больше всего?",
"Что ты чувствуешь, когда я беру тебя за руку на улице?",
"Какой наш отпуск/поездка был идеальным?",
"Что я ем такого странного, но ты уже привык(ла) и любишь?",
"Какой мой жест заботы ты считаешь самым искренним?",
"Что в нас двоих делает нас «не такой парой, как все»?",
"Какой мой взгляд ты любишь ловить на себе?",
"Что ты скрываешь от меня из милой ревности?",
"Какой наш «ленивый» день — твой любимый формат?",
"Что я делаю в постели (сонной) такого милого?",
"Какой мой текст/голосовое тебе всегда поднимает настроение?",
"Что ты хотел(а) бы изменить в наших привычках вместе?",
"Какой момент «я люблю тебя» был самым неожиданным?",
"Что в моей одежде ты тайно крадёшь носить?",
"Какой наш праздник мы отмечаем лучше всех?",
"Что я говорю, когда злюсь, но ты знаешь — это не всерьёз?",
"Какой мой талант ты гордишься больше всего?",
"Что ты чувствуешь, когда мы долго не видимся?",
"Какой наш «секретный» сигнал друг другу?",
"Что в моих прикосновениях тебя всегда заводит (не сексуально, а нежно)?",
"Какой мой недостаток ты уже считаешь частью любви?",
"Что ты хотел(а) бы чаще делать вместе по вечерам?",
"Какой наш разговор ночью был самым глубоким?",
"Что я делаю, когда ты грустишь, и это всегда работает?",
"Какой мой «домашний» аромат ты бы взял(а) с собой в командировку?",
"Что в наших планах на будущее тебя больше всего греет?",
"Какой мой смех ты можешь узнать из тысячи?",
"Что ты ценишь в том, как мы выросли вместе?",
"Если бы ты мог(ла) сказать мне одну вещь, которую редко говоришь — что бы это было?"
],

en:[
"What habit or gesture of mine do you notice first when I'm nervous?",
"What has changed for the better in our relationship over the years?",
"Which day we spent together would you relive exactly the same?",
"What do I do in the mornings that always melts your heart?",
"Which of my 'at-home' looks (in pajamas/no makeup) do you like the most?",
"What habit of mine have you secretly started copying?",
"What scent of mine reminds you of home?",
"When did you realize that we were in it for the long run?",
"What funny or cute things do I say in my sleep?",
"Which of our little rituals (like tea before bed) do you value the most?",
"What has changed about the way I walk since we've been together?",
"Which compliment from me has stayed with you forever?",
"What do you love about the way I hug you?",
"Which of our inside jokes do you remember the most?",
"What do I do when I think you're not looking that secretly touches you?",
"Which gift from me was the most unexpected and sweet?",
"What do you appreciate even during our arguments (like how we make up)?",
"What tone of my voice calms you down instantly?",
"What would you like me to say to you more often?",
"Which of our shared failures turned into the funniest story?",
"What about my smile still catches you even after all these years?",
"Which of my 'tipsy' dances do you like the most?",
"What do you feel when I take your hand in public?",
"Which trip or vacation of ours felt perfect?",
"What strange food do I eat that you've gotten used to and even like now?",
"Which caring gesture from me feels the most genuine?",
"What makes us feel like 'not just any couple'?",
"What kind of look from me do you love catching?",
"What do you secretly hide from me out of cute jealousy?",
"What kind of 'lazy day together' is your favorite?",
"What cute thing do I do when I'm sleepy in bed?",
"Which message or voice note from me always lifts your mood?",
"What habit of ours would you like to change together?",
"Which 'I love you' moment surprised you the most?",
"What piece of my clothing do you secretly steal to wear?",
"Which holiday do we celebrate the best together?",
"What do I say when I'm angry but you know I don't really mean it?",
"Which of my talents are you most proud of?",
"What do you feel when we haven't seen each other for a long time?",
"What is our little 'secret signal' to each other?",
"What about my touch always excites you (not sexually, but tenderly)?",
"Which of my flaws have you already accepted as part of love?",
"What would you like us to do together more often in the evenings?",
"Which late-night conversation of ours was the deepest?",
"What do I do when you're sad that always works?",
"Which of my 'home scents' would you take with you on a business trip?",
"What part of our future plans warms your heart the most?",
"Which of my laughs could you recognize out of a thousand?",
"What do you appreciate about how we've grown together?",
"If you could tell me one thing you rarely say — what would it be?"
],

es:[
"¿Qué gesto mío notas primero cuando estoy nervioso(a)?",
"¿Qué ha cambiado para mejor en nuestra relación con los años?",
"¿Qué día que pasamos juntos te gustaría volver a vivir exactamente igual?",
"¿Qué hago por las mañanas que siempre te enternece?",
"¿Cuál de mis looks de casa (en pijama/sin maquillaje) te gusta más?",
"¿Qué hábito mío has empezado a copiar en secreto?",
"¿Qué olor mío te recuerda a casa?",
"¿En qué momento entendiste que lo nuestro iba en serio?",
"¿Qué digo mientras duermo que te parece más gracioso o tierno?",
"¿Cuál de nuestros pequeños rituales (como el té antes de dormir) valoras más?",
"¿Qué ha cambiado en mi forma de caminar desde que estamos juntos?",
"¿Qué cumplido mío recuerdas para siempre?",
"¿Qué te gusta de la forma en que te abrazo?",
"¿Cuál de nuestros chistes internos recuerdas más?",
"¿Qué hago cuando creo que no me ves que en secreto te conmueve?",
"¿Cuál fue el regalo mío más inesperado y bonito?",
"¿Qué valoras incluso en nuestras discusiones (como cuando hacemos las paces)?",
"¿Qué tono de mi voz te calma al instante?",
"¿Qué te gustaría que te dijera más a menudo?",
"¿Qué fracaso nuestro terminó siendo la historia más divertida?",
"¿Qué de mi sonrisa te sigue atrapando incluso después de años?",
"¿Cuál de mis bailes cuando estoy un poco borracho(a) te gusta más?",
"¿Qué sientes cuando te tomo de la mano en la calle?",
"¿Qué viaje o vacaciones nuestras fueron perfectas?",
"¿Qué comida rara mía ya aceptaste e incluso te gusta?",
"¿Qué gesto de cariño mío te parece el más sincero?",
"¿Qué hace que nosotros seamos una pareja diferente?",
"¿Qué mirada mía te gusta encontrar en ti?",
"¿Qué celito tierno escondes de mí?",
"¿Qué tipo de día perezoso juntos es tu favorito?",
"¿Qué cosa tierna hago cuando estoy medio dormido(a) en la cama?",
"¿Qué mensaje o audio mío siempre te anima?",
"¿Qué hábito nuestro te gustaría cambiar juntos?",
"¿Qué momento de 'te quiero' fue el más inesperado?",
"¿Qué prenda mía sueles robar para ponértela?",
"¿Qué celebración hacemos mejor que nadie?",
"¿Qué digo cuando estoy enfadado(a) pero sabes que no es en serio?",
"¿De qué talento mío te sientes más orgulloso(a)?",
"¿Qué sientes cuando pasamos mucho tiempo sin vernos?",
"¿Cuál es nuestra señal secreta?",
"¿Qué de mis caricias siempre te enciende (de forma tierna, no sexual)?",
"¿Qué defecto mío ya forma parte del amor para ti?",
"¿Qué te gustaría que hiciéramos más juntos por las noches?",
"¿Cuál de nuestras conversaciones nocturnas fue la más profunda?",
"¿Qué hago cuando estás triste que siempre funciona?",
"¿Qué aroma mío de casa te llevarías en un viaje de trabajo?",
"¿Qué parte de nuestros planes de futuro te da más calor al corazón?",
"¿Qué risa mía reconocerías entre mil?",
"¿Qué valoras de cómo hemos crecido juntos?",
"Si pudieras decirme algo que rara vez dices — ¿qué sería?"
],

fr:[
"Quel geste chez moi remarques-tu en premier quand je suis nerveux(se) ?",
"Qu'est-ce qui a changé pour le mieux dans notre relation au fil des années ?",
"Quelle journée passée ensemble aimerais-tu revivre exactement de la même façon ?",
"Que fais-je le matin qui te fait toujours fondre ?",
"Quel de mes looks à la maison (en pyjama/sans maquillage) préfères-tu ?",
"Quelle habitude de moi as-tu secrètement commencé à copier ?",
"Quelle odeur de moi te rappelle la maison ?",
"À quel moment as-tu compris que nous étions faits pour durer ?",
"Qu'est-ce que je dis en dormant qui est le plus drôle ou mignon ?",
"Lequel de nos petits rituels (comme le thé avant de dormir) apprécies-tu le plus ?",
"Qu'est-ce qui a changé dans ma façon de marcher depuis qu'on est ensemble ?",
"Quel compliment de moi n'oublieras-tu jamais ?",
"Qu'aimes-tu dans la façon dont je te serre dans mes bras ?",
"Lequel de nos mèmes ou blagues internes te fait le plus sourire ?",
"Que fais-je quand je pense que tu ne regardes pas et qui te touche en secret ?",
"Quel cadeau de moi t'a le plus surpris et fait plaisir ?",
"Qu'apprécies-tu même dans nos disputes (comme notre façon de nous réconcilier) ?",
"Quel ton de ma voix te calme immédiatement ?",
"Qu'aimerais-tu que je te dise plus souvent ?",
"Quel échec vécu ensemble est devenu l'histoire la plus drôle ?",
"Qu'est-ce qui dans mon sourire t'attire encore après toutes ces années ?",
"Lequel de mes danses quand je suis un peu ivre préfères-tu ?",
"Que ressens-tu quand je te prends la main dans la rue ?",
"Quel voyage ou quelles vacances ensemble étaient parfaits ?",
"Quelle nourriture étrange que je mange as-tu fini par aimer ?",
"Quel geste d'attention de ma part te semble le plus sincère ?",
"Qu'est-ce qui fait que nous sommes un couple différent des autres ?",
"Quel regard de moi aimes-tu surprendre ?",
"Quelle petite jalousie mignonne caches-tu de moi ?",
"Quel type de journée paresseuse ensemble préfères-tu ?",
"Quelle chose mignonne fais-je quand je suis à moitié endormi(e) au lit ?",
"Quel message ou audio de moi te remonte toujours le moral ?",
"Quelle habitude de nous deux aimerais-tu changer ?",
"Quel moment où j'ai dit 'je t'aime' t'a le plus surpris ?",
"Quel vêtement à moi aimes-tu secrètement porter ?",
"Quelle fête célébrons-nous mieux que tout le monde ?",
"Que dis-je quand je suis en colère mais que tu sais que ce n'est pas sérieux ?",
"De quel talent chez moi es-tu le plus fier/fière ?",
"Que ressens-tu quand on ne se voit pas longtemps ?",
"Quel est notre signal secret ?",
"Qu'est-ce qui dans mes gestes tendres t'émeut toujours (pas sexuel, mais affectueux) ?",
"Quel défaut chez moi fais-tu déjà partie de l'amour ?",
"Qu'aimerais-tu que nous fassions plus souvent ensemble le soir ?",
"Quelle conversation nocturne entre nous était la plus profonde ?",
"Que fais-je quand tu es triste qui fonctionne toujours ?",
"Quelle odeur de moi à la maison emporterais-tu en voyage ?",
"Quelle partie de nos projets d'avenir te réchauffe le cœur ?",
"Quel rire de moi reconnaîtrais-tu entre mille ?",
"Qu'apprécies-tu dans la façon dont nous avons grandi ensemble ?",
"Si tu pouvais me dire une chose que tu dis rarement — quelle serait-elle ?"
]

}

const coupleDare = {

ru:[
"Сделай мне массаж плеч 2 минуты, как ты умеешь лучше всего.",
"Расскажи голосом наш любимый момент из первых встреч.",
"Обними меня сзади и просто постой так 30 секунд молча.",
"Напиши мне в заметки телефона «письмо» на 5 предложений о том, за что любишь.",
"Поцелуй меня в 5 разных мест на лице медленно.",
"Станцуй со мной медленный танец под нашу песню (даже если это просто качаться).",
"Покажи фото из галереи, где я тебе особенно нравлюсь.",
"Прошепчи мне на ухо 3 вещи, которые я делаю лучше всех.",
"Сделай мне комплимент за каждую часть тела, которую трогаешь (нежно, 5 штук).",
"Спой мне колыбельную или припев нашей песни тихо.",
"Завяжи мне глаза и покорми чем-то вкусным с рук.",
"Напиши моё имя на спине пальцем и пусть я угадаю слово.",
"Сделай селфи, где мы оба целуемся в щёку глупо.",
"Покажи свою «походку после того, как увидел(а) меня после разлуки».",
"Придумай и исполни 20-секундный рэп о нас двоих.",
"Сделай мне «ледяной поцелуй» с кубиком льда во рту.",
"Потанцуй тверк (или просто смешной танец) сидя у меня на коленях.",
"Напиши «ты мой любимый» помадой на зеркале и сфоткай.",
"Имитируй мой голос и скажи что-то милое от моего лица.",
"Сделай мне засос на шее (маленький, если боишься видного).",
"Покажи, как ты обычно меня целуешь, когда я сплю.",
"Сделай 10 приседаний, а на каждый я целую тебя.",
"Напиши голосовое «спасибо, что ты со мной» максимально искренне.",
"Позволь мне завязать тебе глаза и угадывать запахи продуктов.",
"Сделай мне массаж стоп с поцелуями.",
"Придумай нам новое прозвище и используй его весь вечер.",
"Покажи свою самую старую нашу фотку и расскажи историю.",
"Сделай вид, что мы на первом свидании — флиртуй заново.",
"Напиши на моей руке маркером сердечко и дату нашей встречи.",
"Спой мне серенаду под душем (или просто в комнате).",
"Сделай мне «французский» поцелуй ровно 60 секунд.",
"Покажи, как ты меня обнимаешь, когда я возвращаюсь домой.",
"Съешь что-то сладкое с моего живота без рук.",
"Имитируй мой оргазм смеха (не сексуально, а как я хохочу).",
"Сделай 5 смешных гримас подряд и пусть я выберу лучшую.",
"Позволь мне шлёпнуть тебя по попе 5 раз (игриво).",
"Напиши в мессенджере сообщение, как будто мы поссорились и миримся.",
"Сделай мне массаж головы 2 минуты.",
"Покажи жест «я без тебя не могу» без слов.",
"Сделай селфи наших ног в одной кровати.",
"Произнеси «я люблю тебя» на 3 разных языках.",
"Потанцуй эротично (но мило) под мою любимую песню.",
"Позволь мне написать тебе что-то милое на попе маркером.",
"Сделай вид, что мы в отпуске — позируй для фото.",
"Напиши голосовое с признанием в любви максимально драматично.",
"Сделай мне комплимент каждой части лица за 1 минуту.",
"Покажи, как ты обычно меня будишь по утрам.",
"Придумай и исполни короткий танец «наша любовь».",
"Просто держи мою руку и смотри в глаза 1 минуту без слов.",
"Поцелуй меня так, как будто это наш последний поцелуй сегодня (но нежно)."
],

en:[
"Give me a shoulder massage for 2 minutes the best way you know how.",
"Tell the story of our favorite early-date moment in your voice.",
"Hug me from behind and just stand like that silently for 30 seconds.",
"Write me a short 'letter' in your phone notes with 5 sentences about why you love me.",
"Kiss me slowly in 5 different places on my face.",
"Dance a slow dance with me to our song (even if we just sway).",
"Show a photo from your gallery where you think I look especially good.",
"Whisper in my ear 3 things I do better than anyone.",
"Give me a compliment for every part of my body you touch (gently, 5).",
"Sing me a lullaby or the chorus of our song quietly.",
"Blindfold me and feed me something tasty with your hands.",
"Write my name on my back with your finger and let me guess it.",
"Take a silly selfie where we're both kissing each other's cheek.",
"Show your 'walk after seeing me again after a long time'.",
"Make and perform a 20-second rap about us.",
"Give me an 'ice kiss' with an ice cube in your mouth.",
"Dance twerk (or a funny dance) while sitting on my lap.",
"Write 'you're my favorite' on the mirror with lipstick and take a photo.",
"Imitate my voice and say something cute as if you were me.",
"Give me a small hickey on my neck (if you're brave enough).",
"Show how you usually kiss me when I'm asleep.",
"Do 10 squats and I'll kiss you after each one.",
"Send me a voice message saying 'thank you for being with me' sincerely.",
"Let me blindfold you and guess different food smells.",
"Give me a foot massage with kisses.",
"Come up with a new couple nickname for us and use it all evening.",
"Show our oldest photo together and tell the story behind it.",
"Pretend we're on our first date and flirt with me again.",
"Draw a heart and the date we met on my hand with a marker.",
"Sing me a serenade in the shower (or just in the room).",
"Give me a French kiss for exactly 60 seconds.",
"Show how you hug me when I come back home.",
"Eat something sweet off my stomach without using your hands.",
"Imitate the way I laugh uncontrollably.",
"Make 5 funny faces in a row and let me pick the best.",
"Let me playfully slap your butt 5 times.",
"Write a message in a messenger like we argued and are making up.",
"Give me a 2-minute head massage.",
"Show the gesture 'I can't live without you' without words.",
"Take a selfie of our legs in the same bed.",
"Say 'I love you' in 3 different languages.",
"Dance in a sexy (but cute) way to my favorite song.",
"Let me write something cute on your butt with a marker.",
"Pretend we're on vacation and pose for photos.",
"Send a dramatic voice confession of love.",
"Give me a compliment for every part of my face within 1 minute.",
"Show how you usually wake me up in the morning.",
"Create and perform a short 'our love' dance.",
"Just hold my hand and look into my eyes for 1 minute without speaking.",
"Kiss me like it's our last kiss tonight (but gently)."
],

es:[
"Dame un masaje de hombros durante 2 minutos como mejor sabes.",
"Cuenta con tu voz nuestro momento favorito de las primeras citas.",
"Abrázame por detrás y quédate así en silencio 30 segundos.",
"Escribe en las notas de tu teléfono una carta de 5 frases sobre por qué me amas.",
"Bésame lentamente en 5 lugares diferentes de la cara.",
"Baila conmigo un baile lento con nuestra canción.",
"Muéstrame una foto de tu galería donde creas que salgo especialmente bien.",
"Susúrrame al oído 3 cosas que hago mejor que nadie.",
"Dame un cumplido por cada parte de mi cuerpo que toques suavemente.",
"Cántame una canción de cuna o el estribillo de nuestra canción.",
"Véndame los ojos y dame algo rico de comer con tus manos.",
"Escribe mi nombre en mi espalda con el dedo y déjame adivinar.",
"Haz un selfie tonto donde los dos nos besamos en la mejilla.",
"Muestra tu forma de caminar cuando me ves después de mucho tiempo.",
"Inventa y canta un rap de 20 segundos sobre nosotros.",
"Dame un beso frío con un cubito de hielo en la boca.",
"Baila twerk o un baile divertido sentado en mis piernas.",
"Escribe 'eres mi favorito' con lápiz labial en el espejo y toma una foto.",
"Imita mi voz y di algo tierno como si fueras yo.",
"Hazme un pequeño chupetón en el cuello.",
"Muéstrame cómo me besas cuando estoy dormido(a).",
"Haz 10 sentadillas y te beso cada vez.",
"Envíame un audio diciendo 'gracias por estar conmigo'.",
"Déjame vendarte los ojos y adivinar olores de comida.",
"Dame un masaje de pies con besos.",
"Inventa un apodo de pareja para nosotros y úsalo toda la noche.",
"Muéstrame nuestra foto más antigua y cuenta la historia.",
"Finge que estamos en nuestra primera cita y vuelve a coquetear conmigo.",
"Dibuja un corazón y la fecha en que nos conocimos en mi mano.",
"Cántame una serenata en la ducha o en la habitación.",
"Dame un beso francés durante 60 segundos.",
"Muéstrame cómo me abrazas cuando vuelvo a casa.",
"Come algo dulce de mi vientre sin usar las manos.",
"Imita mi risa incontrolable.",
"Haz 5 caras graciosas seguidas.",
"Déjame darte 5 palmadas juguetonas en el trasero.",
"Escribe un mensaje como si discutiéramos y luego hiciéramos las paces.",
"Dame un masaje de cabeza de 2 minutos.",
"Muestra el gesto 'no puedo vivir sin ti' sin palabras.",
"Haz un selfie de nuestras piernas en la misma cama.",
"Di 'te amo' en 3 idiomas.",
"Baila de forma sensual pero tierna con mi canción favorita.",
"Déjame escribir algo lindo en tu trasero con marcador.",
"Finge que estamos de vacaciones y posa para fotos.",
"Envíame un audio confesando tu amor de forma dramática.",
"Dame cumplidos por cada parte de mi cara en 1 minuto.",
"Muéstrame cómo me despiertas por la mañana.",
"Inventa un pequeño baile llamado 'nuestro amor'.",
"Sostén mi mano y mírame a los ojos 1 minuto sin hablar.",
"Bésame como si fuera nuestro último beso de hoy."
],

fr:[
"Fais-moi un massage des épaules pendant 2 minutes comme tu sais le mieux.",
"Raconte avec ta voix notre moment préféré de nos premières rencontres.",
"Serre-moi dans tes bras par derrière et reste ainsi 30 secondes en silence.",
"Écris dans les notes de ton téléphone une lettre de 5 phrases expliquant pourquoi tu m'aimes.",
"Embrasse-moi lentement à 5 endroits différents sur le visage.",
"Danse un slow avec moi sur notre chanson.",
"Montre-moi une photo de ta galerie où tu me trouves particulièrement beau/belle.",
"Chuchote-moi à l'oreille 3 choses que je fais mieux que tout le monde.",
"Fais-moi un compliment pour chaque partie de mon corps que tu touches doucement.",
"Chante-moi une berceuse ou le refrain de notre chanson.",
"Bande-moi les yeux et donne-moi quelque chose de bon à manger avec tes mains.",
"Écris mon nom sur mon dos avec ton doigt et laisse-moi deviner.",
"Fais un selfie drôle où on s'embrasse sur la joue.",
"Montre ta démarche quand tu me vois après une longue absence.",
"Invente et chante un rap de 20 secondes sur nous.",
"Fais-moi un baiser glacé avec un glaçon dans la bouche.",
"Danse un twerk ou une danse drôle assis sur mes genoux.",
"Écris 'tu es mon préféré' au rouge à lèvres sur le miroir et prends une photo.",
"Imite ma voix et dis quelque chose de mignon comme si tu étais moi.",
"Fais-moi un petit suçon dans le cou.",
"Montre comment tu m'embrasses quand je dors.",
"Fais 10 squats et je t'embrasse à chaque fois.",
"Envoie-moi un message vocal disant 'merci d'être avec moi'.",
"Laisse-moi te bander les yeux et deviner des odeurs de nourriture.",
"Fais-moi un massage des pieds avec des baisers.",
"Invente un surnom de couple pour nous et utilise-le toute la soirée.",
"Montre notre plus vieille photo ensemble et raconte l'histoire.",
"Fais semblant qu'on est à notre premier rendez-vous et drague-moi à nouveau.",
"Dessine un cœur et la date de notre rencontre sur ma main.",
"Chante-moi une sérénade sous la douche ou dans la chambre.",
"Fais-moi un baiser français pendant 60 secondes.",
"Montre comment tu m'embrasses quand je rentre à la maison.",
"Mange quelque chose de sucré sur mon ventre sans utiliser les mains.",
"Imite ma façon de rire aux éclats.",
"Fais 5 grimaces drôles d'affilée.",
"Laisse-moi te donner 5 tapes amusantes sur les fesses.",
"Écris un message comme si on s'était disputés puis réconciliés.",
"Fais-moi un massage de la tête pendant 2 minutes.",
"Montre le geste 'je ne peux pas vivre sans toi' sans parler.",
"Fais un selfie de nos jambes dans le même lit.",
"Dis 'je t'aime' en 3 langues différentes.",
"Danse de façon sensuelle mais mignonne sur ma chanson préférée.",
"Laisse-moi écrire quelque chose de mignon sur tes fesses avec un marqueur.",
"Fais semblant qu'on est en vacances et pose pour des photos.",
"Envoie un message vocal avec une déclaration d'amour dramatique.",
"Fais-moi un compliment pour chaque partie de mon visage en 1 minute.",
"Montre comment tu me réveilles le matin.",
"Invente une petite danse appelée 'notre amour'.",
"Tiens ma main et regarde-moi dans les yeux pendant 1 minute sans parler.",
"Embrasse-moi comme si c'était notre dernier baiser aujourd'hui (mais tendrement)."
]

}
