const dateTruth = {

ru:[
 "Что ты подумал(а) обо мне в первую секунду, когда увидел(а)?",
  "Какой был твой самый смешной провал на свидании до этого?",
  "Какой твой идеальный план выходного дня?",
  "Какую песню ты сейчас чаще всего слушаешь?",
  "Какой твой любимый фильм/сериал, за который тебя могли бы осудить?",
  "Что тебя всегда заставляет улыбаться, даже в плохой день?",
  "Какой твой самый странный пищевой фетиш (типа макароны с кетчупом и т.п.)?",
  "Если бы ты мог(ла) телепортироваться куда угодно прямо сейчас — куда?",
  "Какую супер способность ты бы выбрал(а) и почему?",
  "Какой твой самый большой «виноватый удовольствие» (guilty pleasure)?",
  "Расскажи про самое милое, что кто-то делал для тебя?",
  "Как ты обычно знакомишься с людьми в реальной жизни?",
  "Какой запах тебе нравится больше всего?",
  "Какой твой любимый способ провести дождливый вечер?",
  "Что в людях тебя цепляет сразу?",
  "Какой твой самый неудачный pick-up line, который ты слышал(а) или использовал(а)?",
  "Если бы наша встреча была фильмом — какой жанр?",
  "Какое животное ты больше всего напоминаешь себе и почему?",
  "Что ты всегда берёшь с собой в поездку?",
  "Какой твой любимый мем или шутка, которую ты всем рассказываешь?",
  "Что ты любишь готовить (или заказывать), когда лень?",
  "Какой твой самый яркий детский воспоминание?",
  "Что тебя пугает больше всего в жизни (не страшно, а именно пугает)?",
  "Какой твой любимый праздник и почему?",
  "Если бы ты мог(ла) поужинать с любым человеком (живым или мёртвым) — с кем?",
  "Какой твой тип юмора — сарказм, чёрный, тупой, милый?",
  "Что в моей внешности ты заметил(а) первым?",
  "Какое место в городе ты считаешь самым романтичным?",
  "Какой твой любимый сезон и почему?",
  "Расскажи про самую смешную ситуацию, когда ты краснел(а)?",
  "Что ты делаешь, когда нервничаешь?",
  "Какой твой идеальный завтрак в постель?",
  "Какую книгу/фильм ты бы посоветовал(а) мне прямо сейчас?",
  "Что ты ценишь в людях больше всего?",
  "Какой твой самый большой страх в отношениях?",
  "Как ты обычно заканчиваешь тяжёлый день?",
  "Какое приключение ты бы хотел(а) пережить?",
  "Что тебя всегда вдохновляет?",
  "Какой твой любимый десерт?",
  "Расскажи про момент, когда ты почувствовал(а) себя по-настоящему счастливым(ой) недавно.",
  "Как ты относишься к спонтанным планам?",
  "Какой твой любимый способ сказать «спасибо»?",
  "Что в тебе самом(ой) ты считаешь самым привлекательным?",
  "Какой твой самый большой талант, о котором мало кто знает?",
  "Какое слово или фраза тебя всегда смешит?",
  "Если бы мы снимали TikTok вместе — какой тренд?",
  "Какой твой любимый напиток (алкогольный и без)?",
  "Что ты думаешь о долгих прогулках ночью?",
  "Какой твой самый большой «green flag» в людях?",
  "Что бы ты хотел(а), чтобы я запомнил(а) о тебе после сегодняшнего вечера?"
],

en:[
"What was the very first thing you thought about me when you saw me?",
"What was your funniest dating fail before this?",
"What’s your perfect weekend plan?",
"What song are you listening to the most right now?",
"What’s a movie or series you love that people might judge you for?",
"What always makes you smile, even on a bad day?",
"What’s your weirdest food combo (like pasta with ketchup, etc.)?",
"If you could teleport anywhere right now — where would you go?",
"What superpower would you choose and why?",
"What’s your biggest guilty pleasure?",
"What’s the sweetest thing someone has ever done for you?",
"How do you usually meet people in real life?",
"What smell do you love the most?",
"What’s your favorite way to spend a rainy evening?",
"What instantly attracts you to someone?",
"What’s the worst pick-up line you’ve heard or used?",
"If our meeting were a movie — what genre would it be?",
"What animal do you think you’re most like and why?",
"What’s something you always take with you on a trip?",
"What’s your favorite meme or joke you keep telling people?",
"What do you usually cook (or order) when you’re feeling lazy?",
"What’s one of your most vivid childhood memories?",
"What scares you the most in life (not horror, but real fear)?",
"What’s your favorite holiday and why?",
"If you could have dinner with anyone (alive or dead) — who would it be?",
"What kind of humor do you like — sarcasm, dark, silly, or cute?",
"What was the first thing you noticed about my appearance?",
"What place in the city do you think is the most romantic?",
"What’s your favorite season and why?",
"Tell me about a funny moment when you got really embarrassed.",
"What do you usually do when you’re nervous?",
"What would your perfect breakfast in bed look like?",
"What book or movie would you recommend to me right now?",
"What do you value most in people?",
"What’s your biggest fear in relationships?",
"How do you usually end a tough day?",
"What adventure would you love to experience someday?",
"What always inspires you?",
"What’s your favorite dessert?",
"Tell me about a moment recently when you felt truly happy.",
"How do you feel about spontaneous plans?",
"What’s your favorite way to say 'thank you'?",
"What do you think is the most attractive thing about yourself?",
"What’s a talent you have that not many people know about?",
"What word or phrase always makes you laugh?",
"If we made a TikTok together — what trend would we try?",
"What’s your favorite drink (alcoholic and non-alcoholic)?",
"What do you think about long walks at night?",
"What’s the biggest green flag in people for you?",
"What would you want me to remember about you after tonight?"
],

es:[
"¿Qué fue lo primero que pensaste de mí cuando me viste?",
"¿Cuál fue tu cita más desastrosa pero divertida antes de esta?",
"¿Cómo sería tu fin de semana perfecto?",
"¿Qué canción estás escuchando más últimamente?",
"¿Qué película o serie te encanta pero crees que la gente te juzgaría por ello?",
"¿Qué siempre logra hacerte sonreír incluso en un mal día?",
"¿Cuál es tu combinación de comida más rara (como pasta con ketchup, etc.)?",
"Si pudieras teletransportarte a cualquier lugar ahora mismo — ¿a dónde irías?",
"¿Qué superpoder elegirías y por qué?",
"¿Cuál es tu mayor guilty pleasure?",
"¿Cuál es lo más bonito que alguien ha hecho por ti?",
"¿Cómo sueles conocer gente en la vida real?",
"¿Qué olor te gusta más que ningún otro?",
"¿Cuál es tu forma favorita de pasar una noche lluviosa?",
"¿Qué es lo que te atrae de alguien al instante?",
"¿Cuál es la peor pick-up line que has escuchado o usado?",
"Si nuestro encuentro fuera una película — ¿de qué género sería?",
"¿A qué animal crees que te pareces más y por qué?",
"¿Qué es algo que siempre llevas contigo cuando viajas?",
"¿Cuál es tu meme o broma favorita que siempre cuentas?",
"¿Qué sueles cocinar (o pedir) cuando te da pereza?",
"¿Cuál es uno de tus recuerdos de infancia más vívidos?",
"¿Qué es lo que más miedo te da en la vida (no terror, sino miedo real)?",
"¿Cuál es tu fiesta favorita y por qué?",
"Si pudieras cenar con cualquier persona (viva o muerta) — ¿con quién sería?",
"¿Qué tipo de humor te gusta más — sarcasmo, humor negro, tonto o dulce?",
"¿Qué fue lo primero que notaste de mi apariencia?",
"¿Qué lugar de la ciudad te parece el más romántico?",
"¿Cuál es tu estación favorita y por qué?",
"Cuéntame una situación divertida en la que te pusiste muy rojo(a).",
"¿Qué haces normalmente cuando estás nervioso(a)?",
"¿Cómo sería tu desayuno perfecto en la cama?",
"¿Qué libro o película me recomendarías ahora mismo?",
"¿Qué es lo que más valoras en las personas?",
"¿Cuál es tu mayor miedo en una relación?",
"¿Cómo sueles terminar un día difícil?",
"¿Qué aventura te gustaría vivir alguna vez?",
"¿Qué es lo que siempre te inspira?",
"¿Cuál es tu postre favorito?",
"Cuéntame un momento reciente en el que te sentiste realmente feliz.",
"¿Qué opinas de los planes espontáneos?",
"¿Cuál es tu forma favorita de decir 'gracias'?",
"¿Qué consideras lo más atractivo de ti mismo(a)?",
"¿Cuál es un talento tuyo que poca gente conoce?",
"¿Qué palabra o frase siempre te hace reír?",
"Si hiciéramos un TikTok juntos — ¿qué tendencia intentaríamos?",
"¿Cuál es tu bebida favorita (con alcohol y sin alcohol)?",
"¿Qué opinas de los paseos largos por la noche?",
"¿Cuál es el mayor green flag en una persona para ti?",
"¿Qué te gustaría que recordara de ti después de esta noche?"
],

fr:[
"Quelle a été la toute première chose que tu as pensée de moi quand tu m’as vu(e) ?",
"Quel a été ton rendez-vous le plus raté mais drôle avant celui-ci ?",
"À quoi ressemblerait ton week-end parfait ?",
"Quelle chanson écoutes-tu le plus en ce moment ?",
"Quel film ou quelle série tu adores mais pour lequel on pourrait te juger ?",
"Qu’est-ce qui te fait toujours sourire, même lors d’une mauvaise journée ?",
"Quelle est ta combinaison de nourriture la plus étrange (comme des pâtes avec du ketchup, etc.) ?",
"Si tu pouvais te téléporter n’importe où maintenant — où irais-tu ?",
"Quel super-pouvoir choisirais-tu et pourquoi ?",
"Quel est ton plus grand guilty pleasure ?",
"Quelle est la chose la plus mignonne que quelqu’un ait faite pour toi ?",
"Comment rencontres-tu généralement les gens dans la vraie vie ?",
"Quelle odeur préfères-tu plus que tout ?",
"Quelle est ta façon préférée de passer une soirée pluvieuse ?",
"Qu’est-ce qui t’attire immédiatement chez quelqu’un ?",
"Quelle est la pire pick-up line que tu aies entendue ou utilisée ?",
"Si notre rencontre était un film — quel genre serait-ce ?",
"À quel animal penses-tu ressembler le plus et pourquoi ?",
"Quelle chose emportes-tu toujours avec toi en voyage ?",
"Quel est ton mème ou ta blague préférée que tu racontes tout le temps ?",
"Qu’aimes-tu cuisiner (ou commander) quand tu as la flemme ?",
"Quel est l’un de tes souvenirs d’enfance les plus marquants ?",
"Qu’est-ce qui te fait le plus peur dans la vie (pas l’horreur, mais une vraie peur) ?",
"Quelle est ta fête préférée et pourquoi ?",
"Si tu pouvais dîner avec n’importe qui (vivant ou mort) — avec qui serait-ce ?",
"Quel type d’humour préfères-tu — sarcasme, humour noir, humour idiot ou mignon ?",
"Quelle est la première chose que tu as remarquée dans mon apparence ?",
"Quel endroit de la ville trouves-tu le plus romantique ?",
"Quelle est ta saison préférée et pourquoi ?",
"Raconte-moi une situation drôle où tu as vraiment rougi.",
"Que fais-tu généralement quand tu es nerveux(se) ?",
"À quoi ressemblerait ton petit-déjeuner parfait au lit ?",
"Quel livre ou film me recommanderais-tu maintenant ?",
"Qu’est-ce que tu apprécies le plus chez les gens ?",
"Quelle est ta plus grande peur dans une relation ?",
"Comment termines-tu habituellement une journée difficile ?",
"Quelle aventure aimerais-tu vivre un jour ?",
"Qu’est-ce qui t’inspire toujours ?",
"Quel est ton dessert préféré ?",
"Raconte-moi un moment récent où tu t’es senti(e) vraiment heureux(se).",
"Que penses-tu des plans spontanés ?",
"Quelle est ta façon préférée de dire 'merci' ?",
"Qu’est-ce que tu trouves le plus attirant chez toi ?",
"Quel est un talent que tu as mais que peu de gens connaissent ?",
"Quel mot ou quelle phrase te fait toujours rire ?",
"Si on faisait un TikTok ensemble — quelle tendance essaierait-on ?",
"Quelle est ta boisson préférée (avec alcool et sans alcool) ?",
"Que penses-tu des longues promenades la nuit ?",
"Quel est le plus grand green flag chez une personne pour toi ?",
"Qu’aimerais-tu que je retienne de toi après ce soir ?"
]

}

const dateDare = {

ru:[
"Покажи мне своё самое милое селфи в галерее.",
 "Расскажи голосом из мультика/персонажа любимую фразу. ",
 "Сделай мне комплимент, глядя прямо в глаза 10 секунд. ",
 "Станцуй 15 секунд под любую песню, которую я включу. ",
 "Напиши мне в заметки телефона милое сообщение, как будто мы уже 3 месяца вместе. ",
 "Покажи, как ты обычно флиртуешь взглядом (без слов). ",
  "Сделай вид, что мы на красной дорожке — позируй для «папарацци». ",
  "Произнеси мой ник в телефоне максимально драматично. ",
  "Съешь что-то маленькое (конфету/ягодку) максимально сексу… ой, максимально мило. ",
  "Покажи мне свою самую смешную гримасу. ",
  "Обними меня на 10 секунд (без слов, просто обними). ",
  "Расскажи короткую историю про нас, как будто мы уже год вместе. ",
  "Сделай фото нас двоих и придумай к нему смешной подпись. ",
  "Спой припев любимой песни (можно тихо и фальшиво). ",
  "Покажи, как ты обычно здороваешься с лучшим другом. ",
  "Сделай мне «воздушный поцелуй» максимально театрально. ",
  "Расскажи анекдот или шутку (даже если она плохая). ",
  "Пройдись по комнате модельной походкой. ",
  "Напиши моё имя на ладони и покажи. ",
  "Сделай вид, что ты снимаешь меня на slow-motion камеру. ",
  "Подари мне воображаемый цветок и скажи пару слов. ",
  "Покажи свой «танец радости», когда что-то хорошее случается. ",
  "Прошепчи мне на ухо один комплимент. ",
  "Сделай 5 смешных поз для фото подряд. ",
  "Расскажи, как бы ты меня позвал(а) на второе свидание (голосом). ",
  "Покажи мне свою любимую эмодзи-комбинацию и объясни. ",
  "Сделай массаж плеч мне 20 секунд. ",
  "Придумай нам пару-прозвище прямо сейчас. ",
  "Покажи, как ты обычно смеёшься, когда стесняешься. ",
  "Сделай селфи, где мы оба улыбаемся максимально глупо. ",
  "Расскажи скороговорку быстро 3 раза. ",
  "Покажи жест, которым ты обычно говоришь «вау». ",
  "Напиши мне голосовое сообщение «ты мне нравишься» максимально мило. ",
  "Сделай вид, что мы в кино и ты крадёшь у меня попкорн. ",
  "Покажи свою «походку после удачного свидания». ",
  "Придумай и спой короткую песенку про сегодняшний вечер. ",
  "Сделай мне «high-five» и преврати его в рукопожатие-обнимашку. ",
  "Покажи, как ты обычно прощаешься с друзьями. ",
  "Сделай 10-секундный танец «победа». ",
  "Расскажи мне сон, в котором я был(а) (можно придумать). ",
  "Покажи мне свою «мину точного попадания комплимента». ",
  "Сделай вид, что мы на фотосессии — позируй со мной. ",
  "Произнеси фразу «ты сегодня особенно красив(а)» максимально искренне. ",
  "Покажи, как ты обычно прячешь улыбку, когда стесняешься. ",
  "Сделай мне бумажный самолётик и запусти. ",
  "Расскажи, какой бы ты выбрал(а) нам плейлист для прогулки. ",
  "Покажи жест «я в тебя влюбляюсь» (без слов). ",
  "Сделай вид, что мы в кафе и ты заказываешь за нас обоих. ",
  "Напиши на салфетке (или в заметках) «второе свидание?» и покажи. ",
  "Просто возьми меня за руку на 30 секунд и ничего не говори. "

],

en:[
"Show me your cutest selfie from your gallery.",
"Say your favorite phrase in the voice of a cartoon character.",
"Give me a compliment while looking straight into my eyes for 10 seconds.",
"Dance for 15 seconds to any song I play.",
"Write me a cute message in your phone notes as if we've been together for 3 months.",
"Show how you usually flirt with your eyes (no words).",
"Pretend we're on the red carpet — pose for the 'paparazzi'.",
"Say my nickname from your phone as dramatically as possible.",
"Eat something small (a candy/berry) as cute as possible.",
"Show me your funniest face.",
"Hug me for 10 seconds (no words, just a hug).",
"Tell a short story about us as if we've been together for a year.",
"Take a photo of the two of us and come up with a funny caption.",
"Sing the chorus of your favorite song (quietly and off-key is fine).",
"Show how you usually greet your best friend.",
"Give me a very theatrical air kiss.",
"Tell a joke (even if it's a bad one).",
"Walk across the room like a runway model.",
"Write my name on your palm and show it.",
"Pretend you're filming me in slow motion.",
"Give me an imaginary flower and say a few words.",
"Show your 'happy dance' when something good happens.",
"Whisper one compliment in my ear.",
"Do 5 funny photo poses in a row.",
"Tell me (out loud) how you would ask me on a second date.",
"Show me your favorite emoji combo and explain it.",
"Give me a 20-second shoulder massage.",
"Come up with a couple nickname for us right now.",
"Show how you laugh when you're shy.",
"Take a selfie where we both smile as silly as possible.",
"Say a tongue twister quickly 3 times.",
"Show the gesture you usually make when you say 'wow'.",
"Send me a voice message saying 'I like you' in the cutest way.",
"Pretend we're in a movie theater and you're stealing my popcorn.",
"Show your 'walk after a great date'.",
"Make up and sing a short song about tonight.",
"Give me a high-five and turn it into a handshake-hug.",
"Show how you usually say goodbye to friends.",
"Do a 10-second 'victory dance'.",
"Tell me about a dream where I appeared (you can make it up).",
"Show me your 'that compliment hit perfectly' face.",
"Pretend we're at a photoshoot — pose with me.",
"Say 'you look especially beautiful today' as sincerely as possible.",
"Show how you try to hide your smile when you're shy.",
"Make me a paper airplane and launch it.",
"Tell me what playlist you would choose for our walk.",
"Show the gesture for 'I'm falling for you' (no words).",
"Pretend we're at a café and you're ordering for both of us.",
"Write 'second date?' on a napkin (or in notes) and show it.",
"Just hold my hand for 30 seconds and say nothing."
],

es:[
"Muéstrame tu selfie más bonito de tu galería.",
"Di tu frase favorita con la voz de un personaje de caricatura.",
"Hazme un cumplido mirándome a los ojos durante 10 segundos.",
"Baila 15 segundos con cualquier canción que ponga.",
"Escribe en las notas de tu teléfono un mensaje tierno como si lleváramos 3 meses juntos.",
"Muestra cómo sueles coquetear con la mirada (sin palabras).",
"Imagina que estamos en la alfombra roja — posa para los 'paparazzi'.",
"Di mi nombre en tu teléfono de la forma más dramática posible.",
"Come algo pequeño (un caramelo/una fruta) de la forma más tierna posible.",
"Muéstrame tu cara más graciosa.",
"Abrázame durante 10 segundos (sin hablar, solo un abrazo).",
"Cuenta una pequeña historia sobre nosotros como si lleváramos un año juntos.",
"Haz una foto de nosotros dos e inventa una descripción divertida.",
"Canta el estribillo de tu canción favorita (puede ser bajito y desafinado).",
"Muestra cómo saludas normalmente a tu mejor amigo.",
"Mándame un beso al aire de forma muy teatral.",
"Cuenta un chiste (aunque sea malo).",
"Camina por la habitación como si fueras modelo en una pasarela.",
"Escribe mi nombre en tu mano y enséñalo.",
"Finge que me estás grabando en cámara lenta.",
"Dame una flor imaginaria y di unas palabras.",
"Muéstrame tu 'baile de felicidad' cuando pasa algo bueno.",
"Susúrrame un cumplido al oído.",
"Haz 5 poses graciosas para fotos seguidas.",
"Dime en voz alta cómo me invitarías a una segunda cita.",
"Muéstrame tu combinación de emojis favorita y explícalo.",
"Dame un masaje de hombros durante 20 segundos.",
"Inventa ahora mismo un apodo de pareja para nosotros.",
"Muestra cómo te ríes cuando te da vergüenza.",
"Haz un selfie donde los dos sonriamos lo más tonto posible.",
"Di un trabalenguas rápido 3 veces.",
"Muestra el gesto que haces cuando dices 'wow'.",
"Envíame un mensaje de voz diciendo 'me gustas' de la forma más tierna.",
"Finge que estamos en el cine y me robas las palomitas.",
"Muestra tu 'caminar después de una cita perfecta'.",
"Inventa y canta una pequeña canción sobre esta noche.",
"Choca los cinco conmigo y conviértelo en un saludo-abrazo.",
"Muestra cómo sueles despedirte de tus amigos.",
"Haz un baile de victoria de 10 segundos.",
"Cuéntame un sueño en el que yo aparecía (puedes inventarlo).",
"Muéstrame tu cara de 'ese cumplido dio justo en el blanco'.",
"Finge que estamos en una sesión de fotos — posa conmigo.",
"Di 'hoy te ves especialmente guapo(a)' de la forma más sincera.",
"Muestra cómo escondes tu sonrisa cuando te da vergüenza.",
"Hazme un avión de papel y lánzalo.",
"Dime qué playlist elegirías para nuestro paseo.",
"Muestra el gesto de 'me estoy enamorando de ti' (sin palabras).",
"Finge que estamos en una cafetería y pides por los dos.",
"Escribe '¿segunda cita?' en una servilleta (o en notas) y enséñalo.",
"Simplemente toma mi mano durante 30 segundos y no digas nada."
],

fr:[
"Montre-moi ton selfie le plus mignon dans ta galerie.",
"Dis ta phrase préférée avec la voix d’un personnage de dessin animé.",
"Fais-moi un compliment en me regardant dans les yeux pendant 10 secondes.",
"Danse pendant 15 secondes sur n’importe quelle chanson que je mets.",
"Écris-moi un message mignon dans les notes de ton téléphone comme si on était ensemble depuis 3 mois.",
"Montre comment tu flirtes avec le regard (sans parler).",
"Imagine qu’on est sur le tapis rouge — pose pour les 'paparazzis'.",
"Dis mon nom dans ton téléphone de la façon la plus dramatique possible.",
"Mange quelque chose de petit (bonbon/baie) de la manière la plus mignonne possible.",
"Montre-moi ta grimace la plus drôle.",
"Serre-moi dans tes bras pendant 10 secondes (sans parler).",
"Raconte une petite histoire sur nous comme si on était ensemble depuis un an.",
"Prends une photo de nous deux et invente une légende drôle.",
"Chante le refrain de ta chanson préférée (doucement et faux si tu veux).",
"Montre comment tu salues habituellement ton meilleur ami.",
"Envoie-moi un baiser de loin de façon très théâtrale.",
"Raconte une blague (même si elle est mauvaise).",
"Traverse la pièce comme un mannequin sur un podium.",
"Écris mon nom sur ta paume et montre-le.",
"Fais semblant de me filmer en slow motion.",
"Offre-moi une fleur imaginaire et dis quelques mots.",
"Montre ta 'danse de joie' quand quelque chose de bien arrive.",
"Chuchote-moi un compliment à l’oreille.",
"Fais 5 poses drôles pour une photo d’affilée.",
"Dis-moi à voix haute comment tu m’inviterais à un deuxième rendez-vous.",
"Montre-moi ta combinaison d’emojis préférée et explique-la.",
"Fais-moi un massage des épaules pendant 20 secondes.",
"Invente tout de suite un surnom de couple pour nous.",
"Montre comment tu ris quand tu es gêné(e).",
"Fais un selfie où on sourit tous les deux le plus bêtement possible.",
"Dis un virelangue rapidement 3 fois.",
"Montre le geste que tu fais quand tu dis 'wow'.",
"Envoie-moi un message vocal en disant 'tu me plais' de la façon la plus mignonne.",
"Fais semblant qu’on est au cinéma et que tu me voles du popcorn.",
"Montre ta 'démarche après un super rendez-vous'.",
"Invente et chante une petite chanson sur cette soirée.",
"Fais-moi un high-five et transforme-le en poignée de main-câlin.",
"Montre comment tu dis au revoir à tes amis.",
"Fais une danse de victoire de 10 secondes.",
"Raconte-moi un rêve dans lequel j’apparaissais (tu peux l’inventer).",
"Montre-moi ta tête de 'ce compliment est tombé pile'.",
"Fais semblant qu’on est en séance photo — pose avec moi.",
"Dis 'tu es particulièrement beau/belle aujourd’hui' le plus sincèrement possible.",
"Montre comment tu caches ton sourire quand tu es gêné(e).",
"Fabrique-moi un avion en papier et lance-le.",
"Dis-moi quelle playlist tu choisirais pour notre promenade.",
"Montre le geste pour dire 'je tombe amoureux/amoureuse de toi' (sans parler).",
"Fais semblant qu’on est dans un café et que tu commandes pour nous deux.",
"Écris 'deuxième rendez-vous ?' sur une serviette (ou dans les notes) et montre-le.",
"Prends simplement ma main pendant 30 secondes sans rien dire."
]

}
