const neverCards = {

ru:[
"Я никогда не писал(а) бывшему после одной ночи просто так.",
"Я никогда не фантазировал(а) о поцелуе с кем-то из этой компании прямо сейчас.",
"Я никогда не ставил(а) лайки всем сторис человека, который мне нравится.",
"Я никогда не притворялся(ась), что мне холодно, чтобы меня обняли.",
"Я никогда не отправлял(а) слишком много сердечек за один вечер.",
"Я никогда не подглядывал(а) в телефон crush, когда он или она отходил(а).",
"Я никогда не краснел(а) от комплимента и потом не знал(а), что ответить.",
"Я никогда не флиртовал(а) с баристой ради лишнего сиропа или крема.",
"Я никогда не репостил(а) мем про одиночество, намекая на кого-то.",
"Я никогда не притворялся(ась), что случайно коснулся(ась) руки или ноги.",
"Я никогда не писал(а) «ты сегодня огонь» в три часа ночи.",
"Я никогда не делал(а) скриншот переписки, чтобы показать друзьям.",
"Я никогда не ходил(а) на свидание только ради еды или напитков.",
"Я никогда не забывал(а) имя человека после поцелуя.",
"Я никогда не отправлял(а) голосовое слишком пьяным голосом.",
"Я никогда не ставил(а) чужое фото на аватарку, чтобы вызвать ревность.",
"Я никогда не писал(а) случайное сообщение в четыре утра.",
"Я никогда не краснел(а), когда сказали «вы классная пара».",
"Я никогда не флиртовал(а) в комментариях под сторис.",
"Я никогда не притворялся(ась) пьяным, чтобы поцеловать кого-то.",
"Я никогда не смотрел(а) на губы человека дольше, чем положено.",
"Я никогда не писал(а) длинное признание и потом удалял(а) его.",
"Я никогда не ходил(а) мимо дома crush просто гуляя.",
"Я никогда не улыбался(ась) телефону от одного сообщения.",
"Я никогда не притворялся(ась), что мне нравится та же музыка или фильм.",
"Я никогда не отправлял(а) мем вместо нормального ответа на флирт.",
"Я никогда не краснел(а) от одного долгого взгляда в глаза.",
"Я никогда не писал(а) «спокойной ночи ❤️» человеку, с которым не в отношениях.",
"Я никогда не фантазировал(а) о поцелуе под дождём с кем-то здесь.",
"Я никогда не отправлял(а) фото «случайно» с декольте или без футболки.",
"Я никогда не целовался(ась) в лифте, когда могли зайти.",
"Я никогда не писал(а) «хочу тебя увидеть» после полуночи.",
"Я никогда не краснел(а) от шутки с двойным смыслом.",
"Я никогда не притворялся(ась), что забыл(а) зарядку, чтобы остаться.",
"Я никогда не фантазировал(а) о том, чтобы остаться на ночь после вечеринки.",
"Я никогда не отправлял(а) слишком много эмодзи 🔥😏 подряд.",
"Я никогда не смотрел(а) сторис crush первым делом утром.",
"Я никогда не писал(а) «я скучаю» после одного свидания.",
"Я никогда не краснел(а), когда кто-то поправил мои волосы или одежду.",
"Я никогда не флиртовал(а) в лифте с незнакомцем.",
"Я никогда не делал(а) фото специально для чьих-то глаз.",
"Я никогда не притворялся(ась), что мне страшно в ужастике.",
"Я никогда не отправлял(а) «ты где?» когда человек рядом.",
"Я никогда не писал(а) «ты милый или милая» после одного сообщения.",
"Я никогда не фантазировал(а) о первом поцелуе с кем-то конкретным.",
"Я никогда не краснел(а) от вопроса «а вы пара?».",
"Я никогда не лайкал(а) старые посты, чтобы напомнить о себе.",
"Я никогда не писал(а) «давай потусим» и потом стеснялся(ась).",
"Я никогда не ловил(а) чужой взгляд дольше пяти секунд.",
"Я никогда не отправлял(а) голосовое с улыбкой в голосе.",
 "Я никогда не краснел(а) от фразы «ты сегодня особенно сексуальный или сексуальная».",
"Я никогда не флиртовал(а) в очереди в кафе или магазине.",
"Я никогда не делал(а) комплимент запаху парфюма или одеколона.",
"Я никогда не писал(а) «ты сводишь меня с ума» после флирта.",
"Я никогда не отправлял(а) фото еды с подписью «хочешь попробовать?».",
"Я никогда не краснел(а) от фразы «у тебя крутая улыбка».",
"Я никогда не ставил(а) сердечко случайно на сообщение.",
"Я никогда не притворялся(ась), что потерял(а) дорогу.",
"Я никогда не писал(а) «ты в моих мыслях».",
"Я никогда не фантазировал(а) о совместных прогулках ночью.",
"Я никогда не краснел(а) от лёгкого касания ноги под столом.",
"Я никогда не писал(а) «ты мне нравишься» и сразу не удалял(а) сообщение.",
"Я никогда не отправлял(а) «пришли фотку» без причины.",
"Я никогда не ставил(а) 🔥 под сторис с телом или декольте.",
"Я никогда не целовался(ась) в туалете бара или клуба.",
"Я никогда не писал(а) «приходи, я один или одна дома».",
"Я никогда не краснел(а) от фразы «ты выглядишь так, будто только что…».",
"Я никогда не отправлял(а) голосовое со стонами в шутку.",
"Я никогда не фантазировал(а) о минете или куни от кого-то здесь.",
"Я никогда не писал(а) «хочу тебя» человеку, с которым не целовался(ась).",
"Я никогда не краснел(а) от комплимента про задницу или грудь.",
"Я никогда не отправлял(а) фото в белье «по ошибке».",
"Я никогда не писал(а) «я уже мокрый или мокрая» в чат.",
"Я никогда не фантазировал(а) о сексе в машине или на кухне с кем-то здесь.",
"Я никогда не краснел(а) от случайного касания в интимной зоне.",
"Я никогда не ставил(а) в сторис фото в нижнем белье.",
"Я никогда не писал(а) «давай без слов, просто приходи».",
"Я никогда не отправлял(а) «думаю о тебе и трогаю себя».",
"Я никогда не краснел(а) от шутки «а ты громко стонешь?».",
"Я никогда не фантазировал(а) о том, чтобы попробовать что-то новое с кем-то здесь.",
"Я никогда не писал(а) «хочу услышать, как ты стонешь».",
"Я никогда не целовался(ась) в чужом подъезде или на лестнице.",
"Я никогда не отправлял(а) «кончил(а), думая о тебе».",
"Я никогда не краснел(а) от фразы «я бы тебя трахнул(а)».",
"Я никогда не писал(а) «приходи в одном белье».",
"Я никогда не смотрел(а) на чьи-то руки или губы и думал(а) «хочу их на себе».",
"Я никогда не отправлял(а) фото попки или члена со словами «оцени».",
"Я никогда не фантазировал(а) о грубом или жёстком сексе с кем-то из компании.",
"Я никогда не краснел(а) от фразы «ты выглядишь как после хорошего траха».",
"Я никогда не писал(а) «хочу почувствовать тебя внутри».",
"Я никогда не отправлял(а) стикер с поцелуем вместо нормального текста.",
"Я никогда не фантазировал(а) о том, чтобы остаться наедине после того, как все уйдут.",
"Я никогда не краснел(а) просто потому что человек сказал «ты опасно выглядишь сегодня».",
"Я никогда не писал(а) «ты самый или самая горячий или горячая».",
"Я никогда не отправлял(а) «хочу тебя так сильно, что уже…».",
"Я никогда не целовался(ась) на балконе, пока все были внутри.",
"Я никогда не ставил(а) реакцию 😈 на откровенную сторис.",
"Я никогда не притворялся(ась), что мне нравится, когда меня берут за волосы.",
"Я никогда не писал(а) «давай повторим ту ночь».",
"Я никогда не краснел(а) от мысли, что кто-то здесь знает мои фантазии." 
],

en:[
"I have never texted an ex after a one-night thing just because.",
"I have never fantasized about kissing someone in this group right now.",
"I have never liked every single story of someone I like.",
"I have never pretended to be cold just to get a hug.",
"I have never sent too many hearts in one evening.",
"I have never checked my crush's phone when they walked away.",
"I have never blushed at a compliment and not known what to say.",
"I have never flirted with a barista for extra syrup or cream.",
"I have never reposted a lonely meme hinting at someone.",
"I have never pretended that touching someone's hand or leg was accidental.",
"I have never texted 'you look hot tonight' at 3 AM.",
"I have never taken a screenshot of a chat to show friends.",
"I have never gone on a date just for the food or drinks.",
"I have never forgotten someone's name after kissing them.",
"I have never sent a voice message sounding too drunk.",
"I have never used someone else's photo as my profile picture to make someone jealous.",
"I have never sent a random message at 4 AM.",
"I have never blushed when someone said 'you two make a great couple'.",
"I have never flirted in someone's story comments.",
"I have never pretended to be drunk to kiss someone.",
"I have never stared at someone's lips longer than I should.",
"I have never written a long confession and then deleted it.",
"I have never walked past my crush's house just because.",
"I have never smiled at my phone because of a single message.",
"I have never pretended to like the same music or movie as someone.",
"I have never sent a meme instead of a real reply to flirting.",
"I have never blushed after long eye contact.",
"I have never texted 'good night ❤️' to someone I wasn't dating.",
"I have never imagined kissing someone here in the rain.",
"I have never sent a revealing photo 'by accident'.",
"I have never kissed someone in an elevator where someone could walk in.",
"I have never texted 'I want to see you' after midnight.",
"I have never blushed at a double-meaning joke.",
"I have never pretended I forgot my charger just to stay longer.",
"I have never fantasized about staying overnight after a party.",
"I have never sent too many 🔥😏 emojis in a row.",
"I have never checked my crush's stories first thing in the morning.",
"I have never texted 'I miss you' after one date.",
"I have never blushed when someone fixed my hair or clothes.",
"I have never flirted with a stranger in an elevator.",
"I have never taken a photo meant only for someone's eyes.",
"I have never pretended to be scared during a horror movie.",
"I have never texted 'where are you?' when the person was nearby.",
"I have never called someone cute after one message.",
"I have never imagined a first kiss with someone specific.",
"I have never blushed at the question 'are you two a couple?'.",
"I have never liked old posts just to remind someone about me.",
"I have never said 'let's hang out' and then gotten shy.",
"I have never held someone's gaze for more than five seconds.",
"I have never sent a voice message with a smile in my voice.",
 "I have never blushed when someone said 'you look especially sexy today'.",
"I have never flirted while standing in line at a café or store.",
"I have never complimented someone's perfume or cologne scent.",
"I have never texted 'you drive me crazy' after flirting.",
"I have never sent a photo of food saying 'want a bite?'.",
"I have never blushed when someone said 'you have an amazing smile'.",
"I have never accidentally reacted with a heart to a message.",
"I have never pretended that I was lost.",
"I have never texted 'you're on my mind'.",
"I have never fantasized about walking together at night.",
"I have never blushed from a light touch of legs under the table.",
"I have never typed 'I like you' and immediately deleted it.",
"I have never asked 'send me a photo' without a reason.",
"I have never reacted 🔥 to a revealing story.",
"I have never kissed someone in a bar or club bathroom.",
"I have never texted 'come over, I'm home alone'.",
"I have never blushed at 'you look like you just…'.",
"I have never sent a voice message with fake moaning as a joke.",
"I have never fantasized about oral sex from someone here.",
"I have never texted 'I want you' to someone I haven't kissed.",
"I have never blushed at a compliment about my butt or chest.",
"I have never sent an underwear photo 'by accident'.",
"I have never texted 'I'm already wet or hard' in chat.",
"I have never fantasized about sex in a car or kitchen with someone here.",
"I have never blushed from an accidental intimate touch.",
"I have never posted a story photo in underwear.",
"I have never texted 'no words, just come over'.",
"I have never sent 'I'm thinking about you while touching myself'.",
"I have never blushed at the joke 'do you moan loudly?'.",
"I have never fantasized about trying something new with someone here.",
"I have never texted 'I want to hear you moan'.",
"I have never kissed someone in a random building entrance or stairway.",
"I have never sent 'I finished while thinking about you'.",
"I have never blushed at 'I'd totally sleep with you'.",
"I have never texted 'come over wearing only underwear'.",
"I have never looked at someone's hands or lips and thought 'I want them on me'.",
"I have never sent a photo of my butt or dick saying 'rate it'.",
"I have never fantasized about rough sex with someone in the group.",
"I have never blushed when someone said 'you look like you just had great sex'.",
"I have never texted 'I want to feel you inside me'.",
"I have never sent a kiss sticker instead of real text.",
"I have never imagined staying alone together after everyone leaves.",
"I have never blushed just because someone said 'you look dangerously hot today'.",
"I have never texted 'you're the hottest one here'.",
"I have never sent 'I want you so badly that…'.",
"I have never kissed someone on a balcony while others were inside.",
"I have never reacted 😈 to a provocative story.",
"I have never pretended to enjoy someone pulling my hair.",
"I have never texted 'let's repeat that night'.",
"I have never blushed thinking someone here knows my fantasies." 
],

es:[
"Yo nunca he escrito a un ex después de una sola noche solo porque sí.",
"Yo nunca he fantaseado con besar a alguien de este grupo ahora mismo.",
"Yo nunca he dado like a todas las historias de alguien que me gusta.",
"Yo nunca he fingido tener frío para que me abracen.",
"Yo nunca he enviado demasiados corazones en una noche.",
"Yo nunca he mirado el teléfono de mi crush cuando se alejaba.",
"Yo nunca me he sonrojado por un cumplido sin saber qué decir.",
"Yo nunca he coqueteado con un barista por más jarabe o crema.",
"Yo nunca he repostado un meme sobre la soledad insinuando algo.",
"Yo nunca he fingido que tocar una mano o pierna fue accidental.",
"Yo nunca he escrito 'te ves increíble' a las tres de la mañana.",
"Yo nunca he hecho una captura de pantalla de un chat para enseñarlo.",
"Yo nunca he ido a una cita solo por la comida o bebida.",
"Yo nunca he olvidado el nombre de alguien después de besarlo.",
"Yo nunca he enviado un audio con voz demasiado borracha.",
"Yo nunca he puesto la foto de otra persona como perfil para dar celos.",
"Yo nunca he enviado un mensaje aleatorio a las cuatro de la mañana.",
"Yo nunca me he sonrojado cuando dijeron 'hacen una linda pareja'.",
"Yo nunca he coqueteado en comentarios de historias.",
"Yo nunca he fingido estar borracho para besar a alguien.",
"Yo nunca he mirado los labios de alguien demasiado tiempo.",
"Yo nunca he escrito una confesión larga y luego la he borrado.",
"Yo nunca he pasado por la casa de mi crush sin motivo.",
"Yo nunca he sonreído al teléfono por un solo mensaje.",
"Yo nunca he fingido que me gusta la misma música o película.",
"Yo nunca he respondido a un coqueteo con un meme.",
"Yo nunca me he sonrojado por una mirada larga.",
"Yo nunca he escrito 'buenas noches ❤️' a alguien que no es mi pareja.",
"Yo nunca he imaginado un beso bajo la lluvia con alguien aquí.",
"Yo nunca he enviado una foto sugerente como si fuera casual.",
"Yo nunca he besado a alguien en un ascensor.",
"Yo nunca he escrito 'quiero verte' después de medianoche.",
"Yo nunca me he sonrojado por una broma con doble sentido.",
"Yo nunca he fingido olvidar mi cargador para quedarme más tiempo.",
"Yo nunca he fantaseado con quedarme a dormir después de una fiesta.",
"Yo nunca he enviado demasiados emojis 🔥😏 seguidos.",
"Yo nunca he visto las historias de mi crush al despertar.",
"Yo nunca he escrito 'te extraño' después de una sola cita.",
"Yo nunca me he sonrojado cuando alguien arregló mi ropa o cabello.",
"Yo nunca he coqueteado con un desconocido en un ascensor.",
"Yo nunca he hecho una foto solo para los ojos de alguien.",
"Yo nunca he fingido miedo durante una película de terror.",
"Yo nunca he enviado '¿dónde estás?' cuando la persona estaba cerca.",
"Yo nunca he llamado a alguien lindo después de un mensaje.",
"Yo nunca he imaginado el primer beso con alguien específico.",
"Yo nunca me he sonrojado al oír '¿son pareja?'.",
"Yo nunca he dado like a publicaciones antiguas para llamar la atención.",
"Yo nunca he dicho 'vamos a salir' y luego me dio vergüenza.",
"Yo nunca he mantenido una mirada más de cinco segundos.",
"Yo nunca he enviado un audio con sonrisa en la voz.",
 "Yo nunca me he sonrojado cuando alguien dijo 'hoy te ves especialmente sexy'.",
"Yo nunca he coqueteado mientras hacía fila en un café o tienda.",
"Yo nunca he halagado el olor del perfume o colonia de alguien.",
"Yo nunca he escrito 'me vuelves loco o loca' después de coquetear.",
"Yo nunca he enviado una foto de comida diciendo '¿quieres probar?'.",
"Yo nunca me he sonrojado cuando dijeron 'tienes una sonrisa increíble'.",
"Yo nunca he puesto un corazón por accidente en un mensaje.",
"Yo nunca he fingido que estaba perdido o perdida.",
"Yo nunca he escrito 'estás en mis pensamientos'.",
"Yo nunca he fantaseado con caminar juntos por la noche.",
"Yo nunca me he sonrojado por un ligero toque de piernas bajo la mesa.",
"Yo nunca he escrito 'me gustas' y luego lo he borrado.",
"Yo nunca he pedido 'envía una foto' sin razón.",
"Yo nunca he reaccionado 🔥 a una historia provocativa.",
"Yo nunca he besado a alguien en el baño de un bar o club.",
"Yo nunca he escrito 'ven, estoy solo o sola en casa'.",
"Yo nunca me he sonrojado cuando alguien dijo 'pareces como si acabaras de…'.",
"Yo nunca he enviado un audio con gemidos de broma.",
"Yo nunca he fantaseado con sexo oral de alguien aquí.",
"Yo nunca he escrito 'te deseo' a alguien que no he besado.",
"Yo nunca me he sonrojado por un cumplido sobre mi trasero o pecho.",
"Yo nunca he enviado una foto en ropa interior 'por error'.",
"Yo nunca he escrito 'ya estoy mojado o mojada'.",
"Yo nunca he fantaseado con sexo en el coche o en la cocina con alguien aquí.",
"Yo nunca me he sonrojado por un toque íntimo accidental.",
"Yo nunca he subido una historia en ropa interior.",
"Yo nunca he escrito 'ven sin palabras, solo ven'.",
"Yo nunca he enviado 'estoy pensando en ti mientras me toco'.",
"Yo nunca me he sonrojado por la broma '¿gimes fuerte?'.",
"Yo nunca he fantaseado con probar algo nuevo con alguien aquí.",
"Yo nunca he escrito 'quiero oírte gemir'.",
"Yo nunca he besado a alguien en una escalera o portal ajeno.",
"Yo nunca he enviado 'me corrí pensando en ti'.",
"Yo nunca me he sonrojado cuando alguien dijo 'te follaría'.",
"Yo nunca he escrito 'ven solo en ropa interior'.",
"Yo nunca he mirado manos o labios pensando 'los quiero sobre mí'.",
"Yo nunca he enviado una foto íntima diciendo '¿qué opinas?'.",
"Yo nunca he fantaseado con sexo rudo con alguien del grupo.",
"Yo nunca me he sonrojado cuando alguien dijo 'pareces recién salido del sexo'.",
"Yo nunca he escrito 'quiero sentirte dentro'.",
"Yo nunca he enviado un sticker de beso en lugar de texto.",
"Yo nunca he imaginado quedarme a solas cuando todos se van.",
"Yo nunca me he sonrojado cuando alguien dijo 'hoy te ves peligrosamente sexy'.",
"Yo nunca he escrito 'eres el o la más sexy'.",
"Yo nunca he enviado 'te deseo tanto que ya…'.",
"Yo nunca he besado a alguien en un balcón mientras otros estaban dentro.",
"Yo nunca he reaccionado 😈 a una historia provocativa.",
"Yo nunca he fingido que me gusta que me tiren del pelo.",
"Yo nunca he escrito 'repitamos esa noche'.",
"Yo nunca me he sonrojado pensando que alguien aquí conoce mis fantasías." 
],

fr:[
"Je n'ai jamais écrit à un ex après une nuit juste comme ça.",
"Je n'ai jamais imaginé embrasser quelqu'un de ce groupe maintenant.",
"Je n'ai jamais liké toutes les stories de quelqu'un qui me plaît.",
"Je n'ai jamais prétendu avoir froid pour recevoir un câlin.",
"Je n'ai jamais envoyé trop de cœurs en une soirée.",
"Je n'ai jamais regardé le téléphone de mon crush quand il ou elle partait.",
"Je n'ai jamais rougi après un compliment sans savoir quoi répondre.",
"Je n'ai jamais flirté avec un barista pour plus de sirop ou de crème.",
"Je n'ai jamais reposté un mème sur la solitude pour faire allusion à quelqu'un.",
"Je n'ai jamais fait semblant de toucher quelqu'un par accident.",
"Je n'ai jamais envoyé 'tu es canon' à trois heures du matin.",
"Je n'ai jamais fait une capture d'écran d'un chat pour la montrer.",
"Je n'ai jamais été à un rendez-vous juste pour manger ou boire.",
"Je n'ai jamais oublié le prénom de quelqu'un après l'avoir embrassé.",
"Je n'ai jamais envoyé un message vocal avec une voix trop ivre.",
"Je n'ai jamais mis la photo de quelqu'un d'autre en profil pour rendre jaloux.",
"Je n'ai jamais envoyé un message aléatoire à quatre heures du matin.",
"Je n'ai jamais rougi quand quelqu'un disait 'vous faites un beau couple'.",
"Je n'ai jamais flirté dans les commentaires d'une story.",
"Je n'ai jamais fait semblant d'être ivre pour embrasser quelqu'un.",
"Je n'ai jamais regardé les lèvres de quelqu'un trop longtemps.",
"Je n'ai jamais écrit une longue confession puis l'ai supprimée.",
"Je n'ai jamais passé devant la maison de mon crush sans raison.",
"Je n'ai jamais souri à mon téléphone à cause d'un message.",
"Je n'ai jamais prétendu aimer la même musique ou le même film.",
"Je n'ai jamais répondu à un flirt avec un mème.",
"Je n'ai jamais rougi après un long regard dans les yeux.",
"Je n'ai jamais écrit 'bonne nuit ❤️' à quelqu'un qui n'était pas mon partenaire.",
"Je n'ai jamais imaginé un baiser sous la pluie avec quelqu'un ici.",
"Je n'ai jamais envoyé une photo suggestive comme par hasard.",
"Je n'ai jamais embrassé quelqu'un dans un ascenseur.",
"Je n'ai jamais écrit 'je veux te voir' après minuit.",
"Je n'ai jamais rougi à une blague à double sens.",
"Je n'ai jamais prétendu oublier mon chargeur pour rester.",
"Je n'ai jamais imaginé rester dormir après une fête.",
"Je n'ai jamais envoyé trop d'emojis 🔥😏 d'affilée.",
"Je n'ai jamais regardé les stories de mon crush au réveil.",
"Je n'ai jamais écrit 'tu me manques' après un seul rendez-vous.",
"Je n'ai jamais rougi quand quelqu'un arrangeait mes cheveux ou mes vêtements.",
"Je n'ai jamais flirté avec un inconnu dans un ascenseur.",
"Je n'ai jamais pris une photo destinée aux yeux de quelqu'un.",
"Je n'ai jamais fait semblant d'avoir peur dans un film d'horreur.",
"Je n'ai jamais envoyé 'où es-tu ?' alors que la personne était proche.",
"Je n'ai jamais dit que quelqu'un était mignon après un message.",
"Je n'ai jamais imaginé un premier baiser avec quelqu'un de précis.",
"Je n'ai jamais rougi à la question 'êtes-vous en couple ?'.",
"Je n'ai jamais liké de vieux posts pour attirer l'attention.",
"Je n'ai jamais proposé de sortir puis été trop timide.",
"Je n'ai jamais soutenu un regard plus de cinq secondes.",
"Je n'ai jamais envoyé un message vocal avec un sourire dans la voix.",
 "Je n'ai jamais rougi quand quelqu'un a dit 'tu es particulièrement sexy aujourd'hui'.",
"Je n'ai jamais flirté dans une file d'attente dans un café ou un magasin.",
"Je n'ai jamais complimenté l'odeur du parfum ou de l'eau de Cologne de quelqu'un.",
"Je n'ai jamais écrit 'tu me rends fou ou folle' après avoir flirté.",
"Je n'ai jamais envoyé une photo de nourriture en disant 'tu veux goûter ?'.",
"Je n'ai jamais rougi quand quelqu'un a dit 'tu as un superbe sourire'.",
"Je n'ai jamais mis un cœur par accident sur un message.",
"Je n'ai jamais prétendu être perdu ou perdue.",
"Je n'ai jamais écrit 'tu es dans mes pensées'.",
"Je n'ai jamais fantasmé sur une promenade de nuit ensemble.",
"Je n'ai jamais rougi à cause d'un léger contact de jambes sous la table.",
"Je n'ai jamais écrit 'tu me plais' puis supprimé le message.",
"Je n'ai jamais demandé 'envoie une photo' sans raison.",
"Je n'ai jamais réagi 🔥 à une story provocante.",
"Je n'ai jamais embrassé quelqu'un dans les toilettes d'un bar ou d'un club.",
"Je n'ai jamais écrit 'viens, je suis seul ou seule à la maison'.",
"Je n'ai jamais rougi à la phrase 'tu as l'air de venir de…'.",
"Je n'ai jamais envoyé un message vocal avec des gémissements pour plaisanter.",
"Je n'ai jamais fantasmé sur une fellation ou un cunnilingus venant de quelqu'un ici.",
"Je n'ai jamais écrit 'je te veux' à quelqu'un que je n'ai jamais embrassé.",
"Je n'ai jamais rougi à un compliment sur mes fesses ou ma poitrine.",
"Je n'ai jamais envoyé une photo en sous-vêtements par erreur.",
"Je n'ai jamais écrit 'je suis déjà mouillé ou dur'.",
"Je n'ai jamais fantasmé sur du sexe dans une voiture ou une cuisine avec quelqu'un ici.",
"Je n'ai jamais rougi à un contact intime accidentel.",
"Je n'ai jamais publié une photo en sous-vêtements en story.",
"Je n'ai jamais écrit 'viens sans parler, viens juste'.",
"Je n'ai jamais envoyé 'je pense à toi en me touchant'.",
"Je n'ai jamais rougi à la blague 'tu gémis fort ?'.",
"Je n'ai jamais fantasmé à essayer quelque chose de nouveau avec quelqu'un ici.",
"Je n'ai jamais écrit 'je veux t'entendre gémir'.",
"Je n'ai jamais embrassé quelqu'un dans un escalier ou un hall d'immeuble.",
"Je n'ai jamais envoyé 'j'ai joui en pensant à toi'.",
"Je n'ai jamais rougi à 'je coucherais avec toi'.",
"Je n'ai jamais écrit 'viens seulement en sous-vêtements'.",
"Je n'ai jamais regardé des mains ou des lèvres en pensant 'je les veux sur moi'.",
"Je n'ai jamais envoyé une photo intime en disant 'note ça'.",
"Je n'ai jamais fantasmé sur du sexe brutal avec quelqu'un du groupe.",
"Je n'ai jamais rougi quand quelqu'un a dit 'tu as l'air de sortir d'un bon sexe'.",
"Je n'ai jamais écrit 'je veux te sentir en moi'.",
"Je n'ai jamais envoyé un sticker de baiser au lieu d'un vrai message.",
"Je n'ai jamais imaginé rester seuls après le départ de tout le monde.",
"Je n'ai jamais rougi quand quelqu'un a dit 'tu es dangereusement sexy aujourd'hui'.",
"Je n'ai jamais écrit 'tu es le ou la plus sexy'.",
"Je n'ai jamais envoyé 'je te veux tellement que déjà…'.",
"Je n'ai jamais embrassé quelqu'un sur un balcon pendant que les autres étaient dedans.",
"Je n'ai jamais réagi 😈 à une story provocante.",
"Je n'ai jamais prétendu aimer qu'on me tire les cheveux.",
"Je n'ai jamais écrit 'répétons cette nuit'.",
"Je n'ai jamais rougi en pensant que quelqu'un ici connaît mes fantasmes." 
]

}
